Repository Above-Os/terminus-apps, pull requests merged in 2023-11, with the labels that each got.

#77 [NEW][firefoxm][0.0.1] for test multi entrance
  firefoxm/.helmignore
  firefoxm/Chart.yaml
  firefoxm/app.cfg
  firefoxm/templates/firefox.yaml
  firefoxm/values.yaml
Labels: NEW, waiting to submit

#78 [REMOVE][argoworkflows][0.35.0] remove argo
  argoworkflows/.remove
Labels: REMOVE, waiting to review

#79 [UPDATE][devbox][0.1.3]devbox
  devbox/Chart.yaml
  devbox/app.cfg
  devbox/templates/deployment.yaml
Labels: UPDATE, waiting to review

#80 Update all cfg to 0.1
  argoworkflows/app.cfg
  astral/app.cfg
  astral2/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  devbox/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  firefoxm/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#82 add owners for apps
  argoworkflows/owners
  astral/owners
  astral2/owners
  bazarr/owners
  calendar/owners
  calibre/owners
  calibreweb/owners
  chinesesubfinder/owners
  chromium/owners
  codeserver/owners
  deluge/owners
  denny/owners
  denostr/owners
  devbox/owners
  duplicati/owners
  filebrowser/owners
  firefox/owners
  firefoxm/owners
  geth/owners
  homeassistant/owners
  jellyfin/owners
  lidarr/owners
  mastodon/owners
  miniflux/owners
  n8n/owners
  nastools/owners
  nextcloud/owners
  nextcloud2/owners
  nocodb/owners
  nostream/owners
  nzbget/owners
  obsidian/owners
  openllm/owners
  otmoiclp/owners
  otmoicrelay/owners
  photoprism/owners
  photoview/owners
  portfolio/owners
  prowlarr/owners
  qbittorrent/owners
  radarr/owners
  radicale/owners
  readarr/owners
  rsshub/owners
  sdwebui/owners
  sealcaster/owners
  showdoc/owners
  sickchill/owners
  sonarr/owners
  transmission/owners
Labels: enhancement, waiting to review

#83 fix: update dependencies terminus.version
  devbox/app.cfg
Labels: enhancement, waiting to review

#85 Update Chart.yaml
  astral2/Chart.yaml
Labels: enhancement, waiting to submit

#84 Update app.cfg
  astral2/app.cfg
Labels: enhancement, waiting to submit

#86 fix: update homeassistant categories
  homeassistant/app.cfg
Labels: enhancement, waiting to review

#88 fix: add index for nextcloud
  nextcloud/Chart.yaml
  nextcloud/app.cfg
  nextcloud/index0.json
Labels: enhancement, waiting to review

#89 [NEW][astral3][0.0.14]test
  astral3/.helmignore
  astral3/Chart.yaml
  astral3/app.cfg
  astral3/owners
  astral3/templates/NOTES.txt
  astral3/templates/_helpers.tpl
  astral3/templates/deployment.yaml
  astral3/values.yaml
Labels: NEW, waiting to review

#90 [UPDATE][astral3][0.0.15]OtherContent
  astral3/Chart.yaml
  astral3/app.cfg
Labels: UPDATE, waiting to review

#91 [NEW][astral4][0.0.1]test
  astral4/.helmignore
  astral4/Chart.yaml
  astral4/app.cfg
  astral4/astral3.zip
  astral4/owners
  astral4/templates/NOTES.txt
  astral4/templates/_helpers.tpl
  astral4/templates/deployment.yaml
  astral4/values.yaml
Labels: NEW, waiting to review

#93 [UPDATE][astral2][0.0.16]for test
  astral2/Chart.yaml
  astral2/app.cfg
  astral2/templates/deployment.yaml
Labels: UPDATE, waiting to review

#94 [NEW][astral5][0.0.1]OtherContent
  astral5/.helmignore
  astral5/Chart.yaml
  astral5/app.cfg
  astral5/owners
  astral5/templates/NOTES.txt
  astral5/templates/_helpers.tpl
  astral5/templates/deployment.yaml
  astral5/values.yaml
  values.yaml
Labels: NEW, waiting to review

#95 [UPDATE][astral5][0.0.2]test001
  astral5/Chart.yaml
  astral5/app.cfg
Labels: UPDATE, waiting to review
