Repository Above-Os/terminus-apps, pull requests merged in 2023-09, with the labels that each got.

#3 feat:add n8n
  n8n/.helmignore
  n8n/Chart.yaml
  n8n/app.cfg
  n8n/templates/n8n.yaml
  n8n/templates/postgresql.yaml
  n8n/values.yaml
Labels: ready-for-review

#4 Add nastool
  nastools/.helmignore
  nastools/Chart.yaml
  nastools/app.cfg
  nastools/nastools.png
  nastools/templates/NOTES.txt
  nastools/templates/_helpers.tpl
  nastools/templates/deployment.yaml
  nastools/values.yaml
Labels: ready-for-review

#5 add nextcloud
  nextcloud/.helmignore
  nextcloud/Chart.yaml
  nextcloud/app.cfg
  nextcloud/nextcloud.png
  nextcloud/templates/NOTES.txt
  nextcloud/templates/_helpers.tpl
  nextcloud/templates/deployment.yaml
  nextcloud/values.yaml
Labels: ready-for-review

#9 feat:add nextcloud2 for test
  nextcloud2/.helmignore
  nextcloud2/Chart.yaml
  nextcloud2/app.cfg
  nextcloud2/nextcloud.png
  nextcloud2/templates/NOTES.txt
  nextcloud2/templates/_helpers.tpl
  nextcloud2/templates/deployment.yaml
  nextcloud2/values.yaml
Labels: ready-for-review

#12 [DEV]Add PR template
  .github/pull_request_template.md
Labels: needs-work

#18 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#21 [NEW][calendar][0.0.1]add calendar
  calendar/.helmignore
  calendar/Chart.yaml
  calendar/app.cfg
  calendar/templates/NOTES.txt
  calendar/templates/_helpers.tpl
  calendar/templates/calendar_deploy.yaml
  calendar/values.yaml
Labels: NEW, waiting to review

#22 [NEW][nostream][0.0.1]add nostream
  nostream/.helmignore
  nostream/Chart.yaml
  nostream/app.cfg
  nostream/templates/NOTES.txt
  nostream/templates/_helpers.tpl
  nostream/templates/deployment.yaml
  nostream/values.yaml
Labels: NEW, waiting to review

#23 [NEW][nocodb][0.0.1]add nocodb
  nocodb/Chart.yaml
  nocodb/README.md
  nocodb/app.cfg
  nocodb/templates/deployment.yaml
  nocodb/values.yaml
Labels: NEW, waiting to review

#24 [NEW][nzbget][0.0.1]add nzbget
  nzbget/.helmignore
  nzbget/Chart.yaml
  nzbget/app.cfg
  nzbget/nzbget.png
  nzbget/templates/NOTES.txt
  nzbget/templates/_helpers.tpl
  nzbget/templates/deployment.yaml
  nzbget/values.yaml
Labels: NEW, waiting to review

#25 [UPDATE][nextcloud2][0.0.6]test
  nextcloud2/Chart.yaml
  nextcloud2/app.cfg
  nextcloud2/index0.json
Labels: UPDATE, waiting to review

#26 [UPDATE][sdwebui][0.0.2] change sdwebui requiredGpu: 8Gi
  sdwebui/Chart.yaml
  sdwebui/app.cfg
Labels: UPDATE, waiting to review

#27 [NEW][openllm][0.0.6]
  openllm/Chart.yaml
  openllm/app.cfg
  openllm/templates/deployment.yaml
  openllm/templates/traefik.yaml
  openllm/values.yaml
Labels: NEW, waiting to submit

#28 [UPDATE][nocodb][0.0.2] add permission
  nocodb/Chart.yaml
  nocodb/app.cfg
Labels: UPDATE, waiting to review

#29 [UPDATE][nocodb][0.0.3] update entrance.name to nocodb-svc
  nocodb/Chart.yaml
  nocodb/app.cfg
Labels: UPDATE, waiting to review

#30 [UPDATE][nextcloud2][0.0.7] test
  nextcloud2/Chart.yaml
  nextcloud2/app.cfg
Labels: UPDATE, waiting to review

#31 [UPDATE][nextcloud2][0.0.8] test
  nextcloud2/Chart.yaml
  nextcloud2/app.cfg
Labels: UPDATE, waiting to review

#32 [NEW][astral2][0.0.1]for test
  astral2/.helmignore
  astral2/Chart.yaml
  astral2/app.cfg
  astral2/templates/NOTES.txt
  astral2/templates/_helpers.tpl
  astral2/templates/deployment.yaml
  astral2/values.yaml
Labels: NEW, waiting to review

#33 [UPDATE][astral2][0.0.2] test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to review

#34 [UPDATE][astral2][0.0.3] test
  astral2/Chart.yaml
  astral2/app.cfg
  astral2/templates/deployment.yaml
Labels: UPDATE, waiting to review

#35 [UPDATE][astral2][0.0.4] test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to review

#36 [UPDATE][astral2][0.0.5] test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to review

#37 [UPDATE][astral2][0.0.6] test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to review

#38 [UPDATE][n8n][0.0.1] fix n8n mkdir permission denied
  n8n/templates/n8n.yaml
Labels: UPDATE, waiting to review
