Repository Above-Os/terminus-apps, pull requests merged in 2023-12, with the labels that each got.

#96 [UPDATE][bazarr][0.0.2]test app.cfg
  bazarr/Chart.yaml
  bazarr/app.cfg
  bazarr/templates/deployment.yaml
Labels: UPDATE, waiting to review

#105 Update Test
  codeserver/Chart.yaml
  codeserver/app.cfg
Labels: enhancement, waiting to review

#106 Fix openllm
  openllm/app.cfg
  openllm/templates/deployment.yaml
  openllm/templates/traefik.yaml
Labels: enhancement, waiting to review

#107 add description for sd webui
  sdwebui/app.cfg
Labels: enhancement, waiting to review

#108 [UPDATE][nextcloud][0.0.4]add entranceName
  nextcloud/Chart.yaml
  nextcloud/app.cfg
Labels: UPDATE, waiting to review

#109 Update sd resource requirement
  sdwebui/app.cfg
  sdwebui/templates/deployment.yaml
Labels: enhancement, waiting to review

#110 fix:update some png to webp
  codeserver/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  mastodon/app.cfg
  n8n/app.cfg
  nocodb/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  sdwebui/app.cfg
  showdoc/app.cfg
Labels: enhancement, waiting to review

#112 update all app.cfg to v0.3.0
  argoworkflows/app.cfg
  astral/app.cfg
  astral2/app.cfg
  astral3/app.cfg
  astral4/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  firefoxm/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#116 [NEW][gitlabfusion][0.0.91]Gitlabfusion
  gitlabfusion/Chart.yaml
  gitlabfusion/app.cfg
  gitlabfusion/owners
  gitlabfusion/templates/clientproxy.yaml
  gitlabfusion/templates/gitlab.yaml
  gitlabfusion/templates/serverproxy.yaml
  gitlabfusion/values.yaml
Labels: NEW, waiting to review

#117 [NEW][gitlabfusionclient][0.0.13]Gitlabfusionclient
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/app.cfg
  gitlabfusionclient/owners
  gitlabfusionclient/templates/clientproxy.yaml
  gitlabfusionclient/values.yaml
Labels: NEW, waiting to review

#118 [NEW][gitlabpure][0.0.45]Gitlabpure
  gitlabpure/Chart.yaml
  gitlabpure/app.cfg
  gitlabpure/owners
  gitlabpure/templates/gitlab.yaml
  gitlabpure/values.yaml
Labels: NEW, waiting to review
