Repository Above-Os/terminus-apps, pull requests merged in 2023-10, with the labels that each got.

#39 [UPDATE][astral2][0.0.7]test update
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to review

#40 [UPDATE][nextcloud2][0.0.8]multi line description
  nextcloud2/app.cfg
Labels: UPDATE, waiting to review

#41 [UPDATE][nextcloud2][0.0.8]test description
  nextcloud2/app.cfg
Labels: UPDATE, waiting to review

#42 [UPDATE][openllm][0.0.10]fix ingress
  openllm/Chart.yaml
  openllm/app.cfg
  openllm/templates/traefik.yaml
Labels: UPDATE, waiting to submit

#43 [UPDATE][showdoc][0.0.1]Directory -> DirectoryOrCreate
  showdoc/templates/showdoc.yaml
Labels: UPDATE, waiting to submit

#44 [UPDATE][nextcloud2][0.0.8]test new app.cfg
  nextcloud2/app.cfg
Labels: UPDATE, waiting to review

#47 Update all cfg
  astral/app.cfg
  astral2/.remove
  bazarr/app.cfg
  calendar/.remove
  calibre/app.cfg
  calibreweb/app.cfg
  calibreweb/sonarr.png
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/.remove
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/.remove
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/.remove
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#48 fix: update dependencies terminus vesion
  astral/app.cfg
  bazarr/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  openllm/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#49 [NEW][argoworkflows][0.35.0]add argoworkflows
  argoworkflows/.helmignore
  argoworkflows/Chart.yaml
  argoworkflows/app.cfg
  argoworkflows/ci/default-values.yaml
  argoworkflows/ci/enable-artifact-repo-ref.yaml
  argoworkflows/ci/enable-artifact-repo-values.yaml
  argoworkflows/ci/enable-ingress-values.yaml
  argoworkflows/ci/enable-metrics-values.yaml
  argoworkflows/ci/enable-rbac-values.yaml
  argoworkflows/ci/ha-values.yaml
  argoworkflows/templates/NOTES.txt
  argoworkflows/templates/_helpers.tpl
  argoworkflows/templates/controller/artifact-repository-ref-cm.yaml
  argoworkflows/templates/controller/workflow-aggregate-roles.yaml
  argoworkflows/templates/controller/workflow-controller-cluster-roles.yaml
  argoworkflows/templates/controller/workflow-controller-config-map.yaml
  argoworkflows/templates/controller/workflow-controller-crb.yaml
  argoworkflows/templates/controller/workflow-controller-deployment-pdb.yaml
  argoworkflows/templates/controller/workflow-controller-deployment.yaml
  argoworkflows/templates/controller/workflow-controller-sa.yaml
  argoworkflows/templates/controller/workflow-controller-service.yaml
  argoworkflows/templates/controller/workflow-controller-servicemonitor.yaml
  argoworkflows/templates/controller/workflow-rb.yaml
  argoworkflows/templates/controller/workflow-role.yaml
  argoworkflows/templates/controller/workflow-sa.yaml
  argoworkflows/templates/crds/argoproj.io_clusterworkflowtemplates.yaml
  argoworkflows/templates/crds/argoproj.io_cronworkflows.yaml
  argoworkflows/templates/crds/argoproj.io_workflowartifactgctasks.yaml
  argoworkflows/templates/crds/argoproj.io_workfloweventbindings.yaml
  argoworkflows/templates/crds/argoproj.io_workflows.yaml
  argoworkflows/templates/crds/argoproj.io_workflowtaskresults.yaml
  argoworkflows/templates/crds/argoproj.io_workflowtasksets.yaml
  argoworkflows/templates/crds/argoproj.io_workflowtemplates.yaml
  argoworkflows/templates/extra-manifests.yaml
  argoworkflows/templates/server/gke/backendconfig.yaml
  argoworkflows/templates/server/gke/frontendconfig.yaml
  argoworkflows/templates/server/gke/managedcertificate.yaml
  argoworkflows/templates/server/server-cluster-roles.yaml
  argoworkflows/templates/server/server-crb.yaml
  argoworkflows/templates/server/server-deployment-hpa.yaml
  argoworkflows/templates/server/server-deployment-pdb.yaml
  argoworkflows/templates/server/server-deployment.yaml
  argoworkflows/templates/server/server-ingress.yaml
  argoworkflows/templates/server/server-sa.yaml
  argoworkflows/templates/server/server-service.yaml
  argoworkflows/values.yaml
Labels: NEW, waiting to review

#50 fix:update dependencies terminus version
  argoworkflows/app.cfg
  astral/app.cfg
  bazarr/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#51 [NEW][devbox][0.1.0]DevBox
  devbox/.helmignore
  devbox/Chart.yaml
  devbox/app.cfg
  devbox/devbox.png
  devbox/templates/deployment.yaml
  devbox/values.yaml
Labels: NEW, waiting to submit

#53 [UPDATE][astral2][0.0.8]test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: enhancement, UPDATE

#55 [UPDATE][nextcloud][0.0.2]fix depend
  nextcloud/app.cfg
Labels: UPDATE, waiting to submit

#54 fix:change limit to limited
  argoworkflows/app.cfg
  astral/app.cfg
  astral2/app.cfg
  bazarr/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#56 [UPDATE][astral2][0.0.9]for test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to submit

#57 [UPDATE][astral2][0.0.9]for test
  astral2/app.cfg
Labels: enhancement, waiting to review

#60 [UPDATE][devbox][0.1.1]devbox
  devbox/Chart.yaml
  devbox/app.cfg
  devbox/templates/deployment.yaml
Labels: UPDATE, waiting to review

#62 [UPDATE][astral2][0.0.11]for test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to submit

#64 [UPDATE][astral2][0.0.12]for test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to submit

#61 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, waiting to review

#63 [UPDATE][denostr][0.0.15]Use an externally configured domain name
  denostr/Chart.yaml
  denostr/app.cfg
  denostr/templates/mongodb.yaml
  denostr/templates/traefik.yaml
  denostr/templates/worker.yaml
Labels: UPDATE, waiting to review

#65 [UPDATE][astral2][0.0.13]for test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to submit

#66 [UPDATE][astral2][0.0.14]for test
  astral2/Chart.yaml
  astral2/app.cfg
Labels: UPDATE, waiting to submit

#67 [UPDATE][devbox][0.1.2]devbox
  devbox/Chart.yaml
  devbox/app.cfg
  devbox/templates/deployment.yaml
Labels: UPDATE, waiting to review

#68 fix:modify denostr title
  denostr/app.cfg
Labels: enhancement, waiting to review

#69 [UPDATE][nextcloud][0.0.2]OtherContent
  nextcloud/app.cfg
Labels: UPDATE, waiting to submit

#71 fix:update gpu to 10Gi
  openllm/app.cfg
  sdwebui/app.cfg
Labels: enhancement, waiting to review

#72 Update appcfg to v0.1
  .DS_Store
  .gitignore
  argoworkflows/app.cfg
  astral/app.cfg
  astral2/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  devbox/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#74 Revert "Update appcfg to v0.1"
  .DS_Store
  .gitignore
  argoworkflows/app.cfg
  astral/app.cfg
  astral2/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  devbox/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nextcloud2/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: waiting to submit
