Repository Above-Os/terminus-apps, pull requests merged in 2024-05, with the labels that each got.

#403 [UPDATE][novella][0.0.12]update domain
  novella/Chart.yaml
  novella/TerminusManifest.yaml
  novella/templates/deployment.yaml
Labels: UPDATE

#404 [UPDATE][wordpress][0.0.13] update image repo, improve initial robustness
  wordpress/Chart.yaml
  wordpress/TerminusManifest.yaml
  wordpress/templates/proxy.yaml
Labels: UPDATE, waiting to submit

#405 sync recommend to prod
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/embedding.yaml
  r4business/templates/prerank.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/embedding.yaml
  r4entertainment/templates/prerank.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/embedding.yaml
  r4sport/templates/prerank.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/embedding.yaml
  r4tech/templates/prerank.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
  r4techbiz/templates/prerank.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/embedding.yaml
  r4world/templates/prerank.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: enhancement

#406 [NEW][penpot][0.0.1]add penpot
  penpot/.helmignore
  penpot/Chart.yaml
  penpot/TerminusManifest.yaml
  penpot/owners
  penpot/templates/NOTES.txt
  penpot/templates/_helpers.tpl
  penpot/templates/backend/deployment.yaml
  penpot/templates/backend/service.yaml
  penpot/templates/exporter/deployment.yaml
  penpot/templates/exporter/service.yaml
  penpot/templates/frontend/deployment.yaml
  penpot/templates/frontend/service.yaml
  penpot/templates/redis/deployment.yaml
  penpot/templates/redis/service.yaml
  penpot/values.yaml
Labels: NEW

#408 [UPDATE][nzbget][0.0.7]sync from prod repo
  nzbget/Chart.yaml
  nzbget/TerminusManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE

#409 [NEW][r4entertainment0522][0.1.26]create ent0522
  r4entertainment0522/.helmignore
  r4entertainment0522/Chart.yaml
  r4entertainment0522/README.md
  r4entertainment0522/TerminusManifest.yaml
  r4entertainment0522/owners
  r4entertainment0522/templates/NOTES.txt
  r4entertainment0522/templates/_helpers.tpl
  r4entertainment0522/templates/embedding.yaml
  r4entertainment0522/templates/prerank.yaml
  r4entertainment0522/templates/rank.yaml
  r4entertainment0522/templates/train.yaml
  r4entertainment0522/values.yaml
Labels: NEW

#410 [UPDATE][r4entertainment0522][0.1.27]fix feedname
  r4entertainment0522/Chart.yaml
  r4entertainment0522/TerminusManifest.yaml
Labels: UPDATE

#411 [UPDATE][ipfs][0.0.28]Update ipfs
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/deployment.yaml
Labels: UPDATE

#412 batch add recommend
  r4business0522/.helmignore
  r4business0522/Chart.yaml
  r4business0522/README.md
  r4business0522/TerminusManifest.yaml
  r4business0522/owners
  r4business0522/templates/NOTES.txt
  r4business0522/templates/_helpers.tpl
  r4business0522/templates/embedding.yaml
  r4business0522/templates/prerank.yaml
  r4business0522/templates/rank.yaml
  r4business0522/templates/train.yaml
  r4business0522/values.yaml
  r4sport0522/.helmignore
  r4sport0522/Chart.yaml
  r4sport0522/README.md
  r4sport0522/TerminusManifest.yaml
  r4sport0522/owners
  r4sport0522/templates/NOTES.txt
  r4sport0522/templates/_helpers.tpl
  r4sport0522/templates/embedding.yaml
  r4sport0522/templates/prerank.yaml
  r4sport0522/templates/rank.yaml
  r4sport0522/templates/train.yaml
  r4sport0522/values.yaml
  r4tech0522/.helmignore
  r4tech0522/Chart.yaml
  r4tech0522/README.md
  r4tech0522/TerminusManifest.yaml
  r4tech0522/owners
  r4tech0522/templates/NOTES.txt
  r4tech0522/templates/_helpers.tpl
  r4tech0522/templates/embedding.yaml
  r4tech0522/templates/prerank.yaml
  r4tech0522/templates/rank.yaml
  r4tech0522/templates/train.yaml
  r4tech0522/values.yaml
  r4world0522/.helmignore
  r4world0522/Chart.yaml
  r4world0522/README.md
  r4world0522/TerminusManifest.yaml
  r4world0522/owners
  r4world0522/templates/NOTES.txt
  r4world0522/templates/_helpers.tpl
  r4world0522/templates/embedding.yaml
  r4world0522/templates/prerank.yaml
  r4world0522/templates/rank.yaml
  r4world0522/templates/train.yaml
  r4world0522/values.yaml
Labels: enhancement

#413 [UPDATE][r4business0522][0.1.25]fix app name
  r4business0522/Chart.yaml
  r4business0522/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#414 [UPDATE][farcasterhubble][0.0.24]update info and add readme for test
  farcasterhubble/Chart.yaml
  farcasterhubble/README.md
  farcasterhubble/TerminusManifest.yaml
Labels: UPDATE
