Repository Above-Os/terminus-apps, pull requests merged in 2024-03, with the labels that each got.

#254 suspend apps
  appflowy/.suspend
  bitcoin/.suspend
  bluesky/.suspend
  coracle/.suspend
  dendrite/.suspend
  element/.suspend
  farcaster/.suspend
  firefly/.suspend
  homeassistant/.suspend
  ipfs/.suspend
  joplin/.suspend
  libreddit/.suspend
  libreoffice/.suspend
  nodered/.suspend
  omnivore/.suspend
  onlyoffice/.suspend
  plex/.suspend
  primal/.suspend
  snort/.suspend
  synapse/.suspend
  vaultwarden/.suspend
Labels: enhancement

#257 add owners for homeassistant
  homeassistant/owners
Labels: enhancement

#259 [UPDATE][homeassistant][0.0.13] fix homeassistant install
  homeassistant/.suspend
  homeassistant/Chart.yaml
  homeassistant/app.cfg
  homeassistant/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#261 [UPDATE][homeassistant][0.0.14]fix featured image and title
  homeassistant/Chart.yaml
  homeassistant/app.cfg
Labels: UPDATE

#262 [UPDATE][bytebase][0.0.6]fix bytebase image
  bytebase/Chart.yaml
  bytebase/app.cfg
  bytebase/templates/bytebase.yaml
Labels: UPDATE

#263 [NEW][recommendtest][0.1.6]add recommend test
  recommendtest/.helmignore
  recommendtest/Chart.yaml
  recommendtest/README.md
  recommendtest/app.cfg
  recommendtest/owners
  recommendtest/templates/NOTES.txt
  recommendtest/templates/_helpers.tpl
  recommendtest/templates/embedding.yaml
  recommendtest/templates/recommend.yaml
  recommendtest/templates/train.yaml
  recommendtest/templates/workflow-controller-secrets.yaml
  recommendtest/values.yaml
Labels: NEW

#264 [UPDATE][recommendzhcntech][0.1.5]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/recommend.yaml
Labels: waiting to submit

#265 [UPDATE][recommendworldnews][0.1.7]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
  recommendworldnews/templates/recommend.yaml
Labels: UPDATE

#266 [UPDATE][recommendzhcntech][0.1.5]
  recommendzhcntech/app.cfg
Labels: waiting to submit

#267 [UPDATE][recommendworldnews][0.1.7]
  recommendworldnews/app.cfg
Labels: UPDATE, waiting to submit

#268 [UPDATE][recommendworldnews][0.1.7]
  recommendworldnews/templates/recommend.yaml
Labels: UPDATE, waiting to submit

#269 [UPDATE][recommendzhcntech][0.1.6]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/recommend.yaml
Labels: waiting to submit

#271 [UPDATE][recommendworldnews][0.1.8]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
Labels: UPDATE

#273 [UPDATE][recommendworldnews][0.1.9]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
Labels: UPDATE

#274 [UPDATE][recommendtest][0.1.7]update recommendtest
  recommendtest/Chart.yaml
  recommendtest/app.cfg
  recommendtest/templates/workflow-controller-secrets.yaml
Labels: UPDATE

#278 [UPDATE][recommendtest][0.1.9]
  recommendtest/Chart.yaml
  recommendtest/app.cfg
Labels: UPDATE

#282 [UPDATE][recommendtest][0.1.11]
  recommendtest/.suspend
  recommendtest/Chart.yaml
  recommendtest/app.cfg
  recommendtest/templates/prerank.yaml
  recommendtest/templates/rank.yaml
Labels: UPDATE, waiting to submit

#284 [UPDATE][recommendtest][0.1.12]
  recommendtest/Chart.yaml
  recommendtest/app.cfg
  recommendtest/templates/prerank.yaml
  recommendtest/templates/rank.yaml
  recommendtest/templates/train.yaml
Labels: UPDATE, waiting to submit

#285 [UPDATE][recommendtest][0.1.13]
  recommendtest/Chart.yaml
  recommendtest/app.cfg
  recommendtest/templates/prerank.yaml
Labels: UPDATE

#288 [UPDATE][recommendzhcntech][0.1.8]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/prerank.yaml
Labels: UPDATE

#291 [UPDATE][recommendzhcntech][0.1.9]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/prerank.yaml
  recommendzhcntech/templates/rank.yaml
Labels: UPDATE

#292 [UPDATE][calibreweb][0.0.2]add default credentials and description
  calibreweb/Chart.yaml
  calibreweb/app.cfg
Labels: UPDATE, waiting to submit

#293 [UPDATE][codeserver][0.0.5]add default credentials
  codeserver/Chart.yaml
  codeserver/app.cfg
Labels: UPDATE

#294 [UPDATE][gitlabpure][0.0.47]add Default credentials
  gitlabpure/Chart.yaml
  gitlabpure/app.cfg
Labels: UPDATE

#295 [UPDATE][recommendtest][0.1.14]Update README.md
  recommendtest/Chart.yaml
  recommendtest/README.md
  recommendtest/app.cfg
Labels: UPDATE, waiting to submit

#296 [UPDATE][recommendtest][0.1.15]fix readme format
  recommendtest/Chart.yaml
  recommendtest/README.md
  recommendtest/app.cfg
Labels: UPDATE

#297 [UPDATE][recommendzhcntech][0.1.11]update readme
  recommendzhcntech/Chart.yaml
  recommendzhcntech/README.md
  recommendzhcntech/app.cfg
Labels: UPDATE

#298 [UPDATE][recommendworldnews][0.1.12]update readme
  recommendworldnews/Chart.yaml
  recommendworldnews/README.md
  recommendworldnews/app.cfg
Labels: UPDATE

#303 [UPDATE][radarr][0.0.3]update info
  radarr/Chart.yaml
  radarr/app.cfg
Labels: UPDATE

#302 [UPDATE][readarr][0.0.3]update info
  readarr/Chart.yaml
  readarr/app.cfg
Labels: UPDATE

#301 [UPDATE][prowlarr][0.0.3]update info
  prowlarr/Chart.yaml
  prowlarr/app.cfg
Labels: UPDATE

#300 [UPDATE][sonarr][0.0.2]update info
  sonarr/Chart.yaml
  sonarr/app.cfg
Labels: UPDATE, waiting to submit

#304 [NEW][affine][0.0.1]Add Affine Project
  affine/Chart.yaml
  affine/app.cfg
  affine/owners
  affine/templates/deployment.yaml
  affine/values.yaml
Labels: NEW, waiting to submit

#305 [UPDATE][obsidian][0.0.2]update info
  obsidian/Chart.yaml
  obsidian/app.cfg
  obsidian/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#306 [UPDATE][lidarr][0.0.2]update info
  lidarr/Chart.yaml
  lidarr/app.cfg
Labels: UPDATE

#307 [UPDATE][bazarr][0.0.4]update info
  bazarr/Chart.yaml
  bazarr/app.cfg
Labels: UPDATE

#308 [UPDATE][sickchill][0.0.2]update info
  sickchill/Chart.yaml
  sickchill/app.cfg
Labels: UPDATE

#309 [UPDATE][comfyui][0.0.14]update info
  comfyui/Chart.yaml
  comfyui/app.cfg
Labels: UPDATE

#310 [NEW][recommendt0327][0.0.1]add recommendt0327 for test
  recommendt0327/.helmignore
  recommendt0327/Chart.yaml
  recommendt0327/README.md
  recommendt0327/app.cfg
  recommendt0327/owners
  recommendt0327/templates/NOTES.txt
  recommendt0327/templates/_helpers.tpl
  recommendt0327/templates/embedding.yaml
  recommendt0327/templates/prerank.yaml
  recommendt0327/templates/rank.yaml
  recommendt0327/templates/train.yaml
  recommendt0327/values.yaml
Labels: NEW

#311 [UPDATE][recommendt0327][0.0.2]fix source name error
  recommendt0327/Chart.yaml
  recommendt0327/app.cfg
  recommendt0327/templates/embedding.yaml
  recommendt0327/templates/prerank.yaml
  recommendt0327/templates/rank.yaml
  recommendt0327/templates/train.yaml
Labels: UPDATE

#312 update train and rank to latest 0.1.7
  recommendt0327/templates/train.yaml
  recommendtest/templates/train.yaml
  recommendworldnews/templates/train.yaml
  recommendzhcntech/templates/rank.yaml
  recommendzhcntech/templates/train.yaml
Labels: waiting to submit
