Repository Above-Os/terminus-apps, pull requests merged in 2024-09, with the labels that each got.

#489 [UPDATE][firefox][0.0.5]add i18n
  firefox/Chart.yaml
  firefox/TerminusManifest.yaml
  firefox/i18n/en/TerminusManifest.yaml
  firefox/i18n/zh/TerminusManifest.yaml
  firefox/templates/firefox.yaml
Labels: UPDATE

#490 [UPDATE][firefox][0.0.6]update version
  .idea/.gitignore
  .idea/modules.xml
  .idea/terminus-apps.iml
  .idea/vcs.xml
  firefox/Chart.yaml
  firefox/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#491 [UPDATE][firefox][0.0.6]update i18n
  firefox/i18n/en/TerminusManifest.yaml
  firefox/i18n/zh/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#492 [NEW][prometheus][0.0.3]add placeholder
  prometheus/.helmignore
  prometheus/Chart.yaml
  prometheus/TerminusManifest.yaml
  prometheus/owners
  prometheus/templates/NOTES.txt
  prometheus/templates/_helpers.tpl
  prometheus/templates/deployment.yaml
  prometheus/values.yaml
Labels: NEW, waiting to submit

#494 [NEW][prometheusclient][0.0.3] add app prometheus client
  prometheusclient/.helmignore
  prometheusclient/Chart.yaml
  prometheusclient/TerminusManifest.yaml
  prometheusclient/owners
  prometheusclient/templates/NOTES.txt
  prometheusclient/templates/_helpers.tpl
  prometheusclient/templates/deployment.yaml
  prometheusclient/values.yaml
Labels: NEW, waiting to submit

#496 [UPDATE][affine][0.0.10]test i18n
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/en-US/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#497 [UPDATE][affine][0.0.11]i18n test
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
  affine/owners
Labels: UPDATE

#498 [UPDATE][affine][0.0.12]
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#499 [UPDATE][affine][0.0.13]test i18n
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#500 [UPDATE][affine][0.0.14]i18n test
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#501 [UPDATE][affine][0.0.15]test
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#502 [UPDATE][affine][0.0.16]test affine
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#503 [UPDATE][affine][0.0.17]test
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#504 [UPDATE][affine][0.0.18]
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#505 [UPDATE][affine][0.0.19]Update affine
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE, merged

#506 [UPDATE][affine][0.0.20]
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: UPDATE

#507 [UPDATE][affine][version]test
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: enhancement

#508 Update affine
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: enhancement, waiting to submit

#509 Update affine
  affine/i18n/zh-CN/TerminusManifest.yaml
Labels: enhancement
