Repository Above-Os/terminus-apps, pull requests merged in 2024-02, with the labels that each got.

#222 [UPDATE][bytebase][0.0.5]fix featured image
  bytebase/Chart.yaml
  bytebase/app.cfg
Labels: UPDATE

#223 [SUSPEND][test][0.0.2]suspend app
  test/.suspend
Labels: SUSPEND

#224 Update pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement

#225 [UPDATE][novella][0.0.10]update info
  novella/Chart.yaml
  novella/app.cfg
Labels: UPDATE, waiting to submit

#226 [UPDATE][recommendworldnews][0.1.5]update reademe
  recommendworldnews/Chart.yaml
  recommendworldnews/README.md
  recommendworldnews/app.cfg
Labels: UPDATE

#228 [UPDATE][recommendzhcntech][0.1.4]update md and version
  recommendzhcntech/Chart.yaml
  recommendzhcntech/README.md
  recommendzhcntech/app.cfg
Labels: UPDATE

#227 [UPDATE][recommendworldnews][0.1.6]fix md error
  recommendworldnews/Chart.yaml
  recommendworldnews/README.md
  recommendworldnews/app.cfg
Labels: UPDATE

#230 remove novel
  novella/Chart.yaml
  novella/app.cfg
  novella/owners
  novella/templates/deployment.yaml
  novella/values.yaml
Labels: enhancement

#231 [NEW][novella][0.0.11]add novella
  novella/Chart.yaml
  novella/app.cfg
  novella/owners
  novella/templates/deployment.yaml
  novella/values.yaml
Labels: NEW, waiting to submit

#232 [UPDATE][transmission][0.0.2]update info
  transmission/Chart.yaml
  transmission/app.cfg
Labels: UPDATE

#233 [UPDATE][showdoc][0.0.2]update info
  showdoc/Chart.yaml
  showdoc/app.cfg
Labels: UPDATE

#234 [UPDATE][n8n][0.0.3]Fix featuredImage error
  n8n/Chart.yaml
  n8n/app.cfg
Labels: UPDATE

#235 [UPDATE][radicale][0.0.2]update description and add default credential
  radicale/Chart.yaml
  radicale/app.cfg
Labels: UPDATE, waiting to submit

#236 [UPDATE][photoprism][0.0.4]update default credentials
  photoprism/Chart.yaml
  photoprism/app.cfg
Labels: UPDATE

#237 [UPDATE][miniflux][0.0.2]update info and fix resource error
  miniflux/Chart.yaml
  miniflux/app.cfg
  miniflux/templates/db-deployment.yaml
  miniflux/templates/miniflux-deployment.yaml
Labels: UPDATE

#239 [UPDATE][deluge][0.0.2]update info and add default password
  deluge/Chart.yaml
  deluge/app.cfg
Labels: UPDATE

#240 [UPDATE][omnivore][0.0.2]fix dependencies error
  omnivore/Chart.yaml
  omnivore/app.cfg
Labels: UPDATE

#241 [UPDATE][miniflux][0.0.3]add Default credentials and reduce cpu requirement
  miniflux/Chart.yaml
  miniflux/app.cfg
Labels: UPDATE

#242 [UPDATE][nzbget][0.0.3]bump version for test
  nzbget/Chart.yaml
  nzbget/app.cfg
Labels: UPDATE

#243 [UPDATE][nzbget][0.0.4]bump version for test
  nzbget/Chart.yaml
  nzbget/app.cfg
Labels: UPDATE

#245 [UPDATE][nzbget][0.0.5]bump version for test2
  nzbget/Chart.yaml
  nzbget/app.cfg
Labels: UPDATE

#246 [UPDATE][denostr][0.0.17] fix denostr install
  denostr/Chart.yaml
  denostr/app.cfg
  denostr/templates/traefik.yaml
  denostr/templates/worker.yaml
Labels: UPDATE

#248 [UPDATE][prowlarr][0.0.2]fix prowlarr install
  prowlarr/Chart.yaml
  prowlarr/app.cfg
  prowlarr/templates/deployment.yaml
Labels: UPDATE

#249 [UPDATE][bazarr][0.0.3]fix image
  bazarr/Chart.yaml
  bazarr/app.cfg
  bazarr/owners
  bazarr/templates/deployment.yaml
Labels: UPDATE

#250 [UPDATE][readarr][0.0.2]fix image
  readarr/Chart.yaml
  readarr/app.cfg
  readarr/owners
  readarr/templates/deployment.yaml
Labels: UPDATE

#251 [UPDATE][radarr][0.0.2]fix image
  radarr/Chart.yaml
  radarr/app.cfg
  radarr/owners
  radarr/templates/deployment.yaml
Labels: UPDATE

#252 [UPDATE][nzbget][0.0.6]bump version for test
  nzbget/Chart.yaml
  nzbget/app.cfg
Labels: UPDATE

#253 add secret for workflow
  recommendauto/templates/workflow-controller-secrets.yaml
  recommendbaseball/templates/workflow-controller-secrets.yaml
  recommendbasketball/templates/workflow-controller-secrets.yaml
  recommendbusiness/templates/workflow-controller-secrets.yaml
  recommenddigital/templates/workflow-controller-secrets.yaml
  recommendf1/templates/workflow-controller-secrets.yaml
  recommendfashion/templates/workflow-controller-secrets.yaml
  recommendfood/templates/workflow-controller-secrets.yaml
  recommendfootball/templates/workflow-controller-secrets.yaml
  recommendgaming/templates/workflow-controller-secrets.yaml
  recommendgeek/templates/workflow-controller-secrets.yaml
  recommendgolf/templates/workflow-controller-secrets.yaml
  recommendscience /templates/workflow-controller-secrets.yaml
  recommendsoccer/templates/workflow-controller-secrets.yaml
  recommendsports/templates/workflow-controller-secrets.yaml
  recommendtasken0/templates/workflow-controller-secrets.yaml
  recommendtasken10800/templates/workflow-controller-secrets.yaml
  recommendtaskzhcn0/templates/workflow-controller-secrets.yaml
  recommendtaskzhcn86400/templates/workflow-controller-secrets.yaml
  recommendtechbusiness/templates/workflow-controller-secrets.yaml
  recommendtechnews/templates/workflow-controller-secrets.yaml
  recommendtennis/templates/workflow-controller-secrets.yaml
  recommendtoutiao/templates/workflow-controller-secrets.yaml
  recommendtvmovie/templates/workflow-controller-secrets.yaml
  recommendworldnews/templates/workflow-controller-secrets.yaml
  recommendzhcntech/templates/workflow-controller-secrets.yaml
Labels: enhancement
