Repository Above-Os/terminus-apps, pull requests merged in 2024-04, with the labels that each got.

#320 [UPDATE][affine][0.0.2]
  affine/Chart.yaml
  affine/app.cfg
Labels: UPDATE

#322 [UPDATE][n8n][0.0.4]update n8n to version 0.04
  n8n/Chart.yaml
  n8n/app.cfg
  n8n/templates/n8n.yaml
  n8n/templates/postgresql.yaml
Labels: UPDATE, waiting to submit

#323 [NEW][navidrome][0.0.1]
  navidrome/Chart.yaml
  navidrome/app.cfg
  navidrome/owners
  navidrome/templates/deployment.yaml
  navidrome/values.yaml
Labels: NEW, waiting to submit

#324 [NEW][ghost][0.0.1]
  ghost/Chart.yaml
  ghost/app.cfg
  ghost/owners
  ghost/templates/deployment.yaml
  ghost/values.yaml
Labels: NEW, waiting to submit

#326 [UPDATE][onlyoffice][0.0.2]Pengpeng patch 1
  onlyoffice/.suspend
  onlyoffice/Chart.yaml
  onlyoffice/app.cfg
  onlyoffice/owners
Labels: UPDATE, waiting to submit

#327 [UPDATE][onlyoffice][0.0.3]
  onlyoffice/Chart.yaml
  onlyoffice/app.cfg
  onlyoffice/templates/NOTES.txt
  onlyoffice/templates/_helpers.tpl
  onlyoffice/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#329 [UPDATE][showdoc][0.0.4]fix file access permissions
  showdoc/Chart.yaml
  showdoc/app.cfg
  showdoc/templates/showdoc.yaml
Labels: UPDATE

#330 [UPDATE][n8n][0.0.6]fix config
  n8n/Chart.yaml
  n8n/app.cfg
  n8n/templates/n8n.yaml
Labels: UPDATE, waiting to submit

#331 [UPDATE][recommendzhcntech][0.1.15]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/prerank.yaml
  recommendzhcntech/templates/rank.yaml
Labels: UPDATE, waiting to submit

#333 [UPDATE][recommendworldnews][0.1.17]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
  recommendworldnews/templates/prerank.yaml
  recommendworldnews/templates/rank.yaml
Labels: UPDATE

#335 [UPDATE][recommendworldnews][0.1.18]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
  recommendworldnews/templates/prerank.yaml
  recommendworldnews/templates/rank.yaml
Labels: UPDATE

#337 [UPDATE][recommendtechnews][0.0.7] fix provider error
  recommendtechnews/Chart.yaml
  recommendtechnews/app.cfg
Labels: UPDATE

#340 [UPDATE][recommendworldnews][0.1.19]
  recommendworldnews/Chart.yaml
  recommendworldnews/TerminusManifest.yaml
  recommendworldnews/templates/rank.yaml
Labels: UPDATE

#341 [UPDATE][recommendtechnews][0.0.8]
  recommendtechnews/Chart.yaml
  recommendtechnews/TerminusManifest.yaml
  recommendtechnews/templates/prerank.yaml
  recommendtechnews/templates/rank.yaml
Labels: UPDATE

#342 [UPDATE][navidrome][0.0.2]fix version
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
  navidrome/owners
Labels: enhancement

#343 [UPDATE][ghost][0.0.2]fix version & change open method
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
Labels: enhancement

#345 [UPDATE][navidrome][0.0.3]change open method
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#346 [NEW][llama2chat7bq4][0.0.1]add model llama2
  llama2chat7bq4/.helmignore
  llama2chat7bq4/Chart.yaml
  llama2chat7bq4/README.md
  llama2chat7bq4/TerminusManifest.yaml
  llama2chat7bq4/modelConfig.yaml
  llama2chat7bq4/owners
  llama2chat7bq4/values.yaml
Labels: NEW

#344 add gitignore
  .gitignore
Labels: enhancement

#347 [UPDATE][recommendzhcntech][0.1.16]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/TerminusManifest.yaml
Labels: UPDATE

#352 [UPDATE][otmoiclp][0.0.13]update image and config
  otmoiclp/Chart.yaml
  otmoiclp/TerminusManifest.yaml
  otmoiclp/templates/admin.yaml
  otmoiclp/templates/amm.yaml
  otmoiclp/templates/amm_analytics.yaml
  otmoiclp/templates/analyse.yaml
  otmoiclp/templates/dashboard.yaml
  otmoiclp/templates/dev.yaml
  otmoiclp/templates/evm_avax.yaml
  otmoiclp/templates/evm_bsc.yaml
  otmoiclp/templates/evm_eth.yaml
  otmoiclp/templates/evm_polygon.yaml
  otmoiclp/templates/graphql.yaml
  otmoiclp/templates/lpnode.yaml
  otmoiclp/templates/market.yaml
  otmoiclp/templates/traefik.yaml
  otmoiclp/templates/vc.yaml
Labels: UPDATE

#353 [UPDATE][recommendworldnews][0.1.21]
  recommendworldnews/Chart.yaml
  recommendworldnews/TerminusManifest.yaml
  recommendworldnews/templates/prerank.yaml
  recommendworldnews/templates/rank.yaml
Labels: UPDATE

#354 [UPDATE][recommendzhcntech][0.1.19]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/TerminusManifest.yaml
  recommendzhcntech/templates/prerank.yaml
  recommendzhcntech/templates/rank.yaml
Labels: UPDATE

#355 [NEW][mistralins7bq4][0.0.1]add Mistral 7b
  mistralins7bq4/.helmignore
  mistralins7bq4/Chart.yaml
  mistralins7bq4/README.md
  mistralins7bq4/TerminusManifest.yaml
  mistralins7bq4/modelConfig.yaml
  mistralins7bq4/owners
  mistralins7bq4/values.yaml
Labels: NEW

#357 [UPDATE][ipfs][0.0.2]trans IPFS
  ipfs/.suspend
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
  ipfs/templates/NOTES.txt
  ipfs/templates/_helpers.tpl
  ipfs/templates/deployment.yaml
Labels: UPDATE

#359 [UPDATE][r4sport][0.1.22]fix title and categories
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
Labels: UPDATE

#361 batch fix provider
  r4business/TerminusManifest.yaml
  r4entertainment/TerminusManifest.yaml
  r4sport/TerminusManifest.yaml
  r4tech/TerminusManifest.yaml
Labels: enhancement

#362 [UPDATE][r4tech][0.0.9]
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
Labels: UPDATE

#363 [UPDATE][r4entertainment][0.1.22]fix feed provider and icon
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
Labels: UPDATE

#364 [UPDATE][affine][version]update info & add owners
  affine/Chart.yaml
  affine/TerminusManifest.yaml
  affine/owners
Labels: enhancement

#365 [UPDATE][affine][0.0.4]check chart
  affine/Chart.yaml
  affine/TerminusManifest.yaml
Labels: UPDATE

#366 [UPDATE][ghost][0.0.3]Update info and add owner
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
  ghost/owners
Labels: enhancement

#367 [UPDATE][ghost][0.0.4]fix manifest version
  ghost/Chart.yaml
  ghost/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#368 [UPDATE][navidrome][0.0.4]update spec info
  navidrome/Chart.yaml
  navidrome/TerminusManifest.yaml
Labels: UPDATE

#369 [UPDATE][onlyoffice][0.0.4]update detail
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
Labels: UPDATE

#370 [UPDATE][onlyoffice][0.0.5]fix system dependency
  onlyoffice/Chart.yaml
  onlyoffice/TerminusManifest.yaml
Labels: UPDATE

#371 [UPDATE][ipfs][0.0.3]Update Description
  ipfs/Chart.yaml
  ipfs/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#372 [UPDATE][llama2chat7bq4][0.0.2]test markdown
  llama2chat7bq4/Chart.yaml
  llama2chat7bq4/README.md
  llama2chat7bq4/TerminusManifest.yaml
Labels: UPDATE

#373 [UPDATE][openchat7b][0.0.2]Update Readme & Description
  openchat7b/Chart.yaml
  openchat7b/README.md
  openchat7b/TerminusManifest.yaml
Labels: UPDATE

#374 [UPDATE][yarnmistral7b][0.0.2]add README
  yarnmistral7b/Chart.yaml
  yarnmistral7b/README.md
  yarnmistral7b/TerminusManifest.yaml
Labels: UPDATE

#375 [UPDATE][phi23b][0.0.2]update readme
  phi23b/Chart.yaml
  phi23b/README.md
  phi23b/TerminusManifest.yaml
Labels: UPDATE

#376 [UPDATE][noromaid7b][0.0.2]update readme and some info
  noromaid7b/Chart.yaml
  noromaid7b/README.md
  noromaid7b/TerminusManifest.yaml
Labels: UPDATE

#377 [UPDATE][phi23b][0.0.3]fix chart version
  phi23b/Chart.yaml
  phi23b/TerminusManifest.yaml
Labels: UPDATE

#378 [UPDATE][mistralins7bq4][0.0.2]update info
  mistralins7bq4/Chart.yaml
  mistralins7bq4/README.md
  mistralins7bq4/TerminusManifest.yaml
Labels: UPDATE

#379 [UPDATE][codeninja7bq4][0.0.2]update Readme
  codeninja7bq4/Chart.yaml
  codeninja7bq4/README.md
  codeninja7bq4/TerminusManifest.yaml
Labels: UPDATE

#380 [UPDATE][stealth7b][0.0.2]update README
  stealth7b/Chart.yaml
  stealth7b/README.md
  stealth7b/TerminusManifest.yaml
Labels: UPDATE

#381 [UPDATE][llama2chat7bq4][0.0.3]Update Readme
  llama2chat7bq4/Chart.yaml
  llama2chat7bq4/README.md
  llama2chat7bq4/TerminusManifest.yaml
Labels: UPDATE

#382 [UPDATE][phi23b][0.0.4]add brief intro
  phi23b/Chart.yaml
  phi23b/TerminusManifest.yaml
Labels: UPDATE

#383 [UPDATE][codeninja7bq4][0.0.3]Update
  codeninja7bq4/Chart.yaml
  codeninja7bq4/TerminusManifest.yaml
Labels: UPDATE

#384 [UPDATE][r4world][0.1.22]Update Readme
  r4world/Chart.yaml
  r4world/README.md
  r4world/TerminusManifest.yaml
Labels: UPDATE

#385 [UPDATE][r4world][0.1.23]Update r4world
  r4world/Chart.yaml
  r4world/README.md
  r4world/TerminusManifest.yaml
Labels: UPDATE

#387 [UPDATE][r4world][0.1.25]Update r4world
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
Labels: UPDATE

#388 [UPDATE][r4world][0.1.26]improve readme layout
  r4world/Chart.yaml
  r4world/README.md
  r4world/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#389 [UPDATE][r4techbiz][0.1.20]update description
  r4techbiz/Chart.yaml
  r4techbiz/README.md
  r4techbiz/TerminusManifest.yaml
Labels: UPDATE

#390 [UPDATE][r4tech][0.1.10]update readme
  r4tech/Chart.yaml
  r4tech/README.md
  r4tech/TerminusManifest.yaml
Labels: UPDATE

#391 [UPDATE][r4sport][0.1.23]Update readme
  r4sport/Chart.yaml
  r4sport/README.md
  r4sport/TerminusManifest.yaml
Labels: UPDATE

#392 [UPDATE][r4entertainment][0.1.24]update readme
  r4entertainment/Chart.yaml
  r4entertainment/README.md
  r4entertainment/TerminusManifest.yaml
Labels: UPDATE

#393 [UPDATE][r4business][0.1.22]update readme
  r4business/Chart.yaml
  r4business/README.md
  r4business/TerminusManifest.yaml
Labels: UPDATE

#396 batch fix readme style
  codeninja7bq4/README.md
  codeninja7bq4/TerminusManifest.yaml
  llama2chat7bq4/README.md
  llama2chat7bq4/TerminusManifest.yaml
  mistralins7bq4/README.md
  mistralins7bq4/TerminusManifest.yaml
  noromaid7b/README.md
  noromaid7b/TerminusManifest.yaml
  openchat7b/README.md
  openchat7b/TerminusManifest.yaml
  phi23b/README.md
  phi23b/TerminusManifest.yaml
  r4business/README.md
  r4entertainment/README.md
  r4sport/README.md
  r4tech/README.md
  r4tech/TerminusManifest.yaml
  r4techbiz/README.md
  r4techbiz/TerminusManifest.yaml
  r4world/TerminusManifest.yaml
  stealth7b/README.md
  stealth7b/TerminusManifest.yaml
  yarnmistral7b/README.md
  yarnmistral7b/TerminusManifest.yaml
Labels: enhancement

#397 Update pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#398 fix cover
  codeninja7bq4/TerminusManifest.yaml
  llama2chat7bq4/TerminusManifest.yaml
  mistralins7bq4/TerminusManifest.yaml
  noromaid7b/TerminusManifest.yaml
  openchat7b/TerminusManifest.yaml
  phi23b/TerminusManifest.yaml
  r4business/TerminusManifest.yaml
  r4entertainment/TerminusManifest.yaml
  r4sport/TerminusManifest.yaml
  stealth7b/TerminusManifest.yaml
  yarnmistral7b/TerminusManifest.yaml
Labels: enhancement

#399 [UPDATE][bazarr][0.0.5]bump version for test
  bazarr/Chart.yaml
  bazarr/TerminusManifest.yaml
Labels: UPDATE

#402 batch update version for doc screenshots
  bazarr/Chart.yaml
  bazarr/TerminusManifest.yaml
  photoprism/Chart.yaml
  photoprism/TerminusManifest.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
Labels: enhancement
