Repository Above-Os/terminus-apps, pull requests merged in 2024-01, with the labels that each got.

#119 [UPDATE][nocodb][0.0.3]update description
  nocodb/app.cfg
  nocodb/owners
Labels: enhancement, waiting to review

#121 [UPDATE][nocodb][0.0.5]add upgrade description
  nocodb/Chart.yaml
  nocodb/app.cfg
Labels: enhancement, UPDATE

#122 [UPDATE][gitlabfusionclient][0.0.14]check system password
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/app.cfg
  gitlabfusionclient/templates/clientproxy.yaml
Labels: UPDATE, waiting to review

#123 [UPDATE][gitlabfusion][0.0.92]fix port
  gitlabfusion/Chart.yaml
  gitlabfusion/app.cfg
  gitlabfusion/templates/serverproxy.yaml
Labels: UPDATE, waiting to review

#124 [UPDATE][mastodon][0.0.2]fix resources config
  mastodon/Chart.yaml
  mastodon/app.cfg
  mastodon/templates/all.yaml
Labels: UPDATE, waiting to review

#125 Update all cfg to v0.4
  argoworkflows/app.cfg
  astral/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  firefoxm/app.cfg
  geth/app.cfg
  gitlabfusion/app.cfg
  gitlabfusionclient/app.cfg
  gitlabpure/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  mastodon/app.cfg
  miniflux/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  otmoicrelay/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  showdoc/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#126 [NEW][comfyui][0.0.9]Comfyui
  comfyui/Chart.yaml
  comfyui/app.cfg
  comfyui/owners
  comfyui/templates/deployment.yaml
  comfyui/values.yaml
Labels: NEW, waiting to review

#128 [NEW][bytebase][0.0.21]bytebase
  bytebase/Chart.yaml
  bytebase/app.cfg
  bytebase/owners
  bytebase/templates/bytebase.yaml
  bytebase/templates/proxy.yaml
  bytebase/values.yaml
Labels: NEW, waiting to review

#131 Update bytebase 0.0.2
  bytebase/Chart.yaml
  bytebase/app.cfg
  bytebase/owners
Labels: enhancement, waiting to review

#133 Revert "fix entrance"
  argoworkflows/app.cfg
  astral/app.cfg
  bazarr/app.cfg
  calendar/app.cfg
  calibre/app.cfg
  calibreweb/app.cfg
  chinesesubfinder/app.cfg
  chromium/app.cfg
  codeserver/app.cfg
  deluge/app.cfg
  denny/app.cfg
  denostr/app.cfg
  duplicati/app.cfg
  filebrowser/app.cfg
  firefox/app.cfg
  geth/app.cfg
  homeassistant/app.cfg
  jellyfin/app.cfg
  lidarr/app.cfg
  n8n/app.cfg
  nastools/app.cfg
  nextcloud/app.cfg
  nocodb/app.cfg
  nostream/app.cfg
  nzbget/app.cfg
  obsidian/app.cfg
  openllm/app.cfg
  otmoiclp/app.cfg
  photoprism/app.cfg
  photoview/app.cfg
  portfolio/app.cfg
  prowlarr/app.cfg
  qbittorrent/app.cfg
  radarr/app.cfg
  radicale/app.cfg
  readarr/app.cfg
  rsshub/app.cfg
  sdwebui/app.cfg
  sealcaster/app.cfg
  sickchill/app.cfg
  sonarr/app.cfg
  transmission/app.cfg
Labels: enhancement, waiting to review

#134 [UPDATE][mastodon][0.0.3]add content
  mastodon/Chart.yaml
  mastodon/app.cfg
Labels: UPDATE, waiting to review

#132 [UPDATE][bytebase][0.0.3]Fix entrance name
  bytebase/Chart.yaml
  bytebase/app.cfg
Labels: UPDATE, waiting to review

#135 [UPDATE][mastodon][0.0.4]list mastodon
  mastodon/.nsfw
  mastodon/Chart.yaml
  mastodon/app.cfg
Labels: UPDATE, merged

#136 [UPDATE][homeassistant][0.0.2]add info
  homeassistant/.nsfw
  homeassistant/Chart.yaml
  homeassistant/app.cfg
Labels: UPDATE, merged

#138 [UPDATE][bytebase][0.0.4]fix password
  bytebase/Chart.yaml
  bytebase/app.cfg
  bytebase/templates/proxy.yaml
Labels: UPDATE, waiting to review

#139 [UPDATE][jellyfin][0.0.2]update info
  jellyfin/.nsfw
  jellyfin/Chart.yaml
  jellyfin/app.cfg
Labels: UPDATE, waiting to review

#140 add placeholder apps
  appflowy/.helmignore
  appflowy/Chart.yaml
  appflowy/app.cfg
  appflowy/owners
  appflowy/templates/NOTES.txt
  appflowy/templates/_helpers.tpl
  appflowy/templates/deployment.yaml
  appflowy/values.yaml
  bitcoin/.helmignore
  bitcoin/Chart.yaml
  bitcoin/app.cfg
  bitcoin/owners
  bitcoin/templates/NOTES.txt
  bitcoin/templates/_helpers.tpl
  bitcoin/templates/deployment.yaml
  bitcoin/values.yaml
  bluesky/.helmignore
  bluesky/Chart.yaml
  bluesky/app.cfg
  bluesky/owners
  bluesky/templates/NOTES.txt
  bluesky/templates/_helpers.tpl
  bluesky/templates/deployment.yaml
  bluesky/values.yaml
  dendrite/.helmignore
  dendrite/Chart.yaml
  dendrite/app.cfg
  dendrite/owners
  dendrite/templates/NOTES.txt
  dendrite/templates/_helpers.tpl
  dendrite/templates/deployment.yaml
  dendrite/values.yaml
  ipfs/.helmignore
  ipfs/Chart.yaml
  ipfs/app.cfg
  ipfs/owners
  ipfs/templates/NOTES.txt
  ipfs/templates/_helpers.tpl
  ipfs/templates/deployment.yaml
  ipfs/values.yaml
  libreoffice/.helmignore
  libreoffice/Chart.yaml
  libreoffice/app.cfg
  libreoffice/owners
  libreoffice/templates/NOTES.txt
  libreoffice/templates/_helpers.tpl
  libreoffice/templates/deployment.yaml
  libreoffice/values.yaml
  omnivore/.helmignore
  omnivore/Chart.yaml
  omnivore/app.cfg
  omnivore/owners
  omnivore/templates/NOTES.txt
  omnivore/templates/_helpers.tpl
  omnivore/templates/deployment.yaml
  omnivore/values.yaml
Labels: enhancement, waiting to review

#146 [UPDATE][nocodb][0.0.6]fix icon & remove Readme
  nocodb/Chart.yaml
  nocodb/README.md
  nocodb/app.cfg
Labels: UPDATE, waiting to review

#145 [UPDATE][comfyui][0.0.11]fix icon
  comfyui/Chart.yaml
  comfyui/app.cfg
Labels: UPDATE, waiting to review

#147 [NEW][recommendworldnews][0.0.1]add recommend world news
  recommendworldnews/.helmignore
  recommendworldnews/Chart.yaml
  recommendworldnews/README.md
  recommendworldnews/app.cfg
  recommendworldnews/owners
  recommendworldnews/templates/NOTES.txt
  recommendworldnews/templates/_helpers.tpl
  recommendworldnews/templates/embedding.yaml
  recommendworldnews/templates/recommend.yaml
  recommendworldnews/templates/train.yaml
  recommendworldnews/values.yaml
Labels: NEW, waiting to review

#148 [UPDATE][gitlabfusion][0.0.93]add info
  gitlabfusion/Chart.yaml
  gitlabfusion/app.cfg
Labels: UPDATE, waiting to review

#150 [UPDATE][gitlabpure][0.0.46]update info
  gitlabpure/Chart.yaml
  gitlabpure/app.cfg
Labels: UPDATE, waiting to review

#149 [UPDATE][gitlabfusionclient][0.0.15]update info
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/app.cfg
Labels: UPDATE, waiting to review

#152 [UPDATE][photoprism][0.0.2]add info
  photoprism/.nsfw
  photoprism/Chart.yaml
  photoprism/app.cfg
Labels: UPDATE, waiting to review

#151 [UPDATE][geth][0.0.2]add info
  geth/.nsfw
  geth/Chart.yaml
  geth/app.cfg
  geth/templates/geth.yaml
  geth/templates/traefik.yaml
  geth/templates/website.yaml
Labels: UPDATE, waiting to review

#155 [NEW][wordpress][0.0.2]new app wordpress
  wordpress/Chart.yaml
  wordpress/app.cfg
  wordpress/owners
  wordpress/templates/wordpress.yaml
  wordpress/values.yaml
Labels: NEW, waiting to review

#154 [UPDATE][n8n][0.0.2]add info
  n8n/.nsfw
  n8n/Chart.yaml
  n8n/app.cfg
Labels: UPDATE, waiting to review

#156 listing apps
  astral/.nsfw
  bazarr/.nsfw
  calibre/.nsfw
  calibreweb/.nsfw
  chinesesubfinder/.nsfw
  chromium/.nsfw
  codeserver/.nsfw
  deluge/.nsfw
  denny/.nsfw
  denostr/.nsfw
  duplicati/.nsfw
  filebrowser/.nsfw
  firefox/.nsfw
  lidarr/.nsfw
  miniflux/.nsfw
  nextcloud/.nsfw
  nostream/.nsfw
  nzbget/.nsfw
  obsidian/.nsfw
  obsidian/.remove
  openllm/.nsfw
  otmoiclp/.suspend
  otmoicrelay/.suspend
  photoview/.nsfw
  prowlarr/.nsfw
  qbittorrent/.nsfw
  radarr/.nsfw
  radicale/.nsfw
  readarr/.nsfw
  sealcaster/.nsfw
  showdoc/.nsfw
  sickchill/.nsfw
  sonarr/.nsfw
  transmission/.nsfw
Labels: enhancement, waiting to review

#158 [NEW][onlyoffice][0.0.1]add onlyoffice
  onlyoffice/.helmignore
  onlyoffice/Chart.yaml
  onlyoffice/app.cfg
  onlyoffice/owners
  onlyoffice/templates/NOTES.txt
  onlyoffice/templates/_helpers.tpl
  onlyoffice/templates/deployment.yaml
  onlyoffice/values.yaml
Labels: NEW, waiting to review

#159 [UPDATE][farcaster][0.0.2]update info
  farcaster/Chart.yaml
  farcaster/app.cfg
Labels: UPDATE, waiting to review

#160 [UPDATE][sealcaster][0.0.2]add promote image and change icon
  sealcaster/Chart.yaml
  sealcaster/app.cfg
Labels: UPDATE, waiting to review

#161 [UPDATE][nostream][0.0.2]update info
  nostream/Chart.yaml
  nostream/app.cfg
Labels: UPDATE, waiting to review

#163 Fix chartname
  coracle/Chart.yaml
  element/Chart.yaml
  firefly/Chart.yaml
  joplin/Chart.yaml
  libreddit/Chart.yaml
  nodered/Chart.yaml
  plex/Chart.yaml
  primal/Chart.yaml
  snort/Chart.yaml
  synapse/Chart.yaml
  vaultwarden/Chart.yaml
Labels: enhancement, waiting to review

#164 [UPDATE][coracle][0.0.2]update info
  coracle/Chart.yaml
  coracle/app.cfg
Labels: UPDATE, waiting to review

#165 [UPDATE][element][0.0.2]update info
  element/Chart.yaml
  element/app.cfg
Labels: UPDATE, waiting to review

#167 [UPDATE][joplin][0.0.2]change icon
  joplin/Chart.yaml
  joplin/app.cfg
Labels: UPDATE, waiting to review

#173 [UPDATE][snort][0.0.2]change icon
  snort/Chart.yaml
  snort/app.cfg
Labels: UPDATE, waiting to review

#172 [UPDATE][primal][0.0.2]change icon
  primal/Chart.yaml
  primal/app.cfg
Labels: UPDATE, waiting to review

#171 [UPDATE][plex][0.0.2]change icon
  plex/Chart.yaml
  plex/app.cfg
Labels: UPDATE, waiting to review

#170 [UPDATE][nodered][0.0.2]change icon
  nodered/Chart.yaml
  nodered/app.cfg
Labels: UPDATE, waiting to review

#169 [UPDATE][libreddit][0.0.2]change icon
  libreddit/Chart.yaml
  libreddit/app.cfg
Labels: UPDATE, waiting to review

#168 [UPDATE][vaultwarden][0.0.2]change icon
  vaultwarden/Chart.yaml
  vaultwarden/app.cfg
Labels: UPDATE, waiting to review

#174 [UPDATE][wordpress][0.0.3]wordpress add proxy
  wordpress/Chart.yaml
  wordpress/app.cfg
  wordpress/templates/proxy.yaml
  wordpress/templates/wordpress.yaml
Labels: UPDATE, waiting to review

#175 [UPDATE][comfyui][0.0.12]fix config namespace
  comfyui/Chart.yaml
  comfyui/app.cfg
  comfyui/templates/deployment.yaml
Labels: UPDATE, waiting to review

#166 [UPDATE][firefly][0.0.2]OtherContent
  firefly/Chart.yaml
  firefly/app.cfg
Labels: UPDATE, waiting to review

#178 [UPDATE][wordpress][0.0.4] fix x-frame-options
  wordpress/Chart.yaml
  wordpress/app.cfg
  wordpress/templates/proxy.yaml
Labels: UPDATE, waiting to review

#162 [UPDATE][synapse][0.0.2]update info and fix icon
  synapse/Chart.yaml
  synapse/app.cfg
Labels: UPDATE, waiting to review

#179 [UPDATE][jellyfin][0.0.3]add clients
  jellyfin/Chart.yaml
  jellyfin/app.cfg
Labels: UPDATE, waiting to review

#180 [NEW][test][0.0.1]submit test app
  test/Chart.yaml
  test/app.cfg
  test/index0.json
  test/owners
  test/templates/gitlab.yaml
  test/values.yaml
Labels: NEW, waiting to review

#181 [UPDATE][test][0.0.2]add policy
  test/Chart.yaml
  test/app.cfg
Labels: UPDATE, waiting to review

#182 recommend source
  recommendtasken0/templates/recommend.yaml
  recommendtasken10800/templates/recommend.yaml
  recommendtasken10800/templates/train.yaml
  recommendtaskzhcn0/templates/recommend.yaml
  recommendtaskzhcn0/templates/train.yaml
  recommendtaskzhcn86400/templates/recommend.yaml
  recommendtaskzhcn86400/templates/train.yaml
Labels: enhancement, waiting to submit

#183 add owner for recommends
  recommendauto/owners
  recommendbaseball/owners
  recommendbasketball/owners
  recommendbusiness/owners
  recommenddigital/owners
  recommendf1/owners
  recommendfashion/owners
  recommendfood/owners
  recommendfootball/owners
  recommendgaming/owners
  recommendgeek/owners
  recommendgolf/owners
  recommendscience /owners
  recommendsoccer/owners
  recommendsports/owners
  recommendtechbusiness/owners
  recommendtechnews/owners
  recommendtennis/owners
  recommendtoutiao/owners
  recommendtvmovie/owners
  recommendworldnews/owners
Labels: enhancement, waiting to review

#186 [UPDATE][recommendworldnews][0.0.2]bump version
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
Labels: UPDATE, waiting to review

#185 [UPDATE][recommendzhcntech][0.0.2]fix chart
  recommendzhcntech/Chart.yaml
  recommendzhcntech/README.md
  recommendzhcntech/app.cfg
  recommendzhcntech/owners
Labels: enhancement, UPDATE, waiting to submit

#189 Update recommendzhcntech 0.0.3
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/owners
Labels: enhancement, waiting to review

#190 [UPDATE][recommendzhcntech][0.0.4]bump version
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
Labels: UPDATE, waiting to review

#192 Dev yt
  firefox/Chart.yaml
  firefox/app.cfg
  firefox/owners
Labels: enhancement, waiting to review

#193 [UPDATE][firefox][0.0.3]update for test
  firefox/Chart.yaml
  firefox/app.cfg
Labels: UPDATE, waiting to review

#200 [UPDATE][recommendworldnews][0.1.2]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
  recommendworldnews/templates/embedding.yaml
  recommendworldnews/templates/recommend.yaml
  recommendworldnews/templates/train.yaml
Labels: UPDATE, waiting to review

#199 [SUSPEND][recommendtaskzhcn0][0.0.1]Create .suspend
  recommendtaskzhcn0/.suspend
Labels: SUSPEND, waiting to review

#198 [SUSPEND][recommendtaskzhcn86400][0.0.1]Create .suspend
  recommendtaskzhcn86400/.suspend
Labels: SUSPEND, waiting to review

#197 [SUSPEND][recommendtasken10800][0.0.1]Create .suspend
  recommendtasken10800/.suspend
Labels: SUSPEND, waiting to review

#196 [SUSPEND][recommendtasken0][0.0.1]Create .suspend
  recommendtasken0/.suspend
Labels: SUSPEND, waiting to review

#195 [SUSPEND][recommendtechbusiness][0.0.1]suspend recommend
  recommendtechbusiness/.suspend
Labels: SUSPEND, waiting to review

#201 [UPDATE][recommendzhcntech][0.1.2]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/embedding.yaml
  recommendzhcntech/templates/recommend.yaml
  recommendzhcntech/templates/train.yaml
Labels: UPDATE, waiting to review

#202 [UPDATE][wordpress][0.0.5]update info
  wordpress/Chart.yaml
  wordpress/app.cfg
Labels: UPDATE, waiting to review

#205 [UPDATE][astral][0.0.2]bump version2
  astral/Chart.yaml
  astral/app.cfg
Labels: UPDATE, waiting to review

#206 [UPDATE][comfyui][0.0.13]fix CPU error
  comfyui/Chart.yaml
  comfyui/app.cfg
Labels: UPDATE, waiting to review

#207 reduce cpu request
  astral/app.cfg
  astral/templates/deployment.yaml
  bazarr/app.cfg
  bazarr/templates/deployment.yaml
  calibre/app.cfg
  calibre/templates/deployment.yaml
  calibreweb/app.cfg
  calibreweb/templates/deployment.yaml
  chinesesubfinder/app.cfg
  chinesesubfinder/templates/chinesesubfinder.yaml
  codeserver/app.cfg
  codeserver/templates/chartmuseum.yaml
  codeserver/templates/codeserver.yaml
  deluge/app.cfg
  deluge/templates/deployment.yaml
  denny/app.cfg
  denny/templates/denny.yaml
  duplicati/app.cfg
  duplicati/templates/deployment.yaml
  filebrowser/app.cfg
  filebrowser/templates/deployment.yaml
  homeassistant/app.cfg
  homeassistant/templates/deployment.yaml
  lidarr/app.cfg
  lidarr/templates/deployment.yaml
  nzbget/app.cfg
  nzbget/templates/deployment.yaml
  photoprism/app.cfg
  photoprism/templates/deployment.yaml
  photoview/app.cfg
  photoview/templates/deployment.yaml
  prowlarr/app.cfg
  prowlarr/templates/deployment.yaml
  qbittorrent/app.cfg
  qbittorrent/templates/deployment.yaml
  radarr/app.cfg
  radarr/templates/deployment.yaml
  radicale/app.cfg
  radicale/templates/all.yaml
  readarr/app.cfg
  readarr/templates/deployment.yaml
  sealcaster/app.cfg
  sealcaster/templates/deployment.yaml
  sickchill/app.cfg
  sickchill/templates/deployment.yaml
  sonarr/app.cfg
  sonarr/templates/deployment.yaml
  transmission/app.cfg
  transmission/templates/deployment.yaml
Labels: enhancement, waiting to review

#208 [UPDATE][qbittorrent][0.0.2] update info
  qbittorrent/Chart.yaml
  qbittorrent/app.cfg
Labels: UPDATE, waiting to review

#209 [UPDATE][dendrite][0.0.2]fix denpendency
  dendrite/Chart.yaml
  dendrite/app.cfg
Labels: UPDATE, waiting to review

#210 [UPDATE][recommendworldnews][0.1.3]
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
  recommendworldnews/templates/embedding.yaml
  recommendworldnews/templates/recommend.yaml
  recommendworldnews/templates/train.yaml
Labels: UPDATE, waiting to review

#211 [UPDATE][recommendzhcntech][0.1.3]
  recommendzhcntech/Chart.yaml
  recommendzhcntech/app.cfg
  recommendzhcntech/templates/embedding.yaml
  recommendzhcntech/templates/recommend.yaml
  recommendzhcntech/templates/train.yaml
Labels: UPDATE, waiting to review

#212 [UPDATE][gitlabfusionclient][0.0.16]reduce cpu request
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/app.cfg
Labels: UPDATE, waiting to review

#215 [UPDATE][photoview][0.0.2]update info
  photoview/Chart.yaml
  photoview/app.cfg
Labels: UPDATE, waiting to review

#214 [UPDATE][astral][0.0.3]update info
  astral/Chart.yaml
  astral/app.cfg
Labels: UPDATE, waiting to review

#213 [UPDATE][codeserver][0.0.4]update info
  codeserver/Chart.yaml
  codeserver/app.cfg
Labels: UPDATE, waiting to review

#216 [UPDATE][wordpress][0.0.6]add policy
  wordpress/Chart.yaml
  wordpress/app.cfg
Labels: UPDATE, waiting to submit

#217 [UPDATE][recommendworldnews][0.1.4]fix version name
  recommendworldnews/Chart.yaml
  recommendworldnews/app.cfg
Labels: UPDATE

#218 [UPDATE][gitlabfusion][0.0.94]support login root
  gitlabfusion/Chart.yaml
  gitlabfusion/app.cfg
  gitlabfusion/templates/clientproxy.yaml
  gitlabfusion/templates/serverproxy.yaml
Labels: UPDATE

#219 [UPDATE][gitlabfusionclient][0.0.17]create password on install app
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/app.cfg
  gitlabfusionclient/templates/clientproxy.yaml
Labels: UPDATE, waiting to submit

#220 [NEW][novella][0.0.8]new app novella
  novella/Chart.yaml
  novella/app.cfg
  novella/owners
  novella/templates/deployment.yaml
  novella/values.yaml
Labels: NEW

#221 [UPDATE][novella][0.0.9]Update description
  novella/Chart.yaml
  novella/app.cfg
Labels: UPDATE, waiting to submit
