Repository Above-Os/terminus-apps, pull requests merged in 2024-07, with the labels that each got.

#454 [NEW][immich][0.0.1]add immich placeholder
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/owners
  immich/templates/deployment.yaml
  immich/values.yaml
Labels: NEW, waiting to submit

#455 batch add app placeholder
  appsmith/Chart.yaml
  appsmith/TerminusManifest.yaml
  appsmith/owners
  appsmith/templates/deployment.yaml
  appsmith/values.yaml
  mattermost/Chart.yaml
  mattermost/TerminusManifest.yaml
  mattermost/owners
  mattermost/templates/deployment.yaml
  mattermost/values.yaml
  memos/Chart.yaml
  memos/TerminusManifest.yaml
  memos/owners
  memos/templates/deployment.yaml
  memos/values.yaml
  odoo/Chart.yaml
  odoo/TerminusManifest.yaml
  odoo/owners
  odoo/templates/deployment.yaml
  odoo/values.yaml
  paperless/Chart.yaml
  paperless/TerminusManifest.yaml
  paperless/owners
  paperless/templates/deployment.yaml
  paperless/values.yaml
  rocketchat/Chart.yaml
  rocketchat/TerminusManifest.yaml
  rocketchat/owners
  rocketchat/templates/deployment.yaml
  rocketchat/values.yaml
  supabase/Chart.yaml
  supabase/TerminusManifest.yaml
  supabase/owners
  supabase/templates/deployment.yaml
  supabase/values.yaml
Labels: enhancement

#456 bump version for test
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/owners
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/owners
Labels: enhancement

#457 add dify
  difyfusion/.helmignore
  difyfusion/Chart.yaml
  difyfusion/TerminusManifest.yaml
  difyfusion/owners
  difyfusion/templates/NOTES.txt
  difyfusion/templates/_helpers.tpl
  difyfusion/templates/deployment.yaml
  difyfusion/values.yaml
  difyfusionclient/.helmignore
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
  difyfusionclient/owners
  difyfusionclient/templates/NOTES.txt
  difyfusionclient/templates/_helpers.tpl
  difyfusionclient/templates/dify_fe_deploy.yaml
  difyfusionclient/values.yaml
Labels: enhancement

#458 [UPDATE][difyfusionclient][0.0.2]fix: auto connect
  difyfusionclient/Chart.yaml
  difyfusionclient/TerminusManifest.yaml
  difyfusionclient/templates/dify_fe_deploy.yaml
Labels: UPDATE, waiting to submit

#460 test legacy api: add provider register and permission
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement

#461 Test legacy api
  prowlarr/templates/deployment.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement, waiting to submit

#462 Test legacy api
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement, invalid

#463 Test legacy api
  prowlarr/Chart.yaml
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement

#464 fix: datatype and endpoint
  prowlarr/Chart.yaml
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement, waiting to submit

#465 Test legacy api
  prowlarr/Chart.yaml
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement

#467 Test legacy api
  prowlarr/Chart.yaml
  prowlarr/TerminusManifest.yaml
  sonarr/Chart.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
Labels: enhancement

#468 Test legacy api
  bazarr/TerminusManifest.yaml
  bazarr/templates/deployment.yaml
  deluge/templates/deployment.yaml
  nzbget/templates/deployment.yaml
  prowlarr/TerminusManifest.yaml
  prowlarr/templates/deployment.yaml
  qbittorrent/templates/deployment.yaml
  sonarr/TerminusManifest.yaml
  sonarr/templates/deployment.yaml
  transmission/templates/deployment.yaml
Labels: enhancement

#469 [UPDATE][transmission][0.0.4]fix provider and add arm64 tag test2
  transmission/Chart.yaml
  transmission/TerminusManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#471 [UPDATE][immich][0.0.14]
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/deployment.yaml
  immich/templates/machine-learning.yaml
  immich/templates/server.yaml
Labels: UPDATE

#475 Update owners
  immich/owners
Labels: enhancement

#476 [UPDATE][immich][0.0.15]
  immich/Chart.yaml
  immich/TerminusManifest.yaml
  immich/templates/machine-learning.yaml
  immich/templates/server.yaml
Labels: UPDATE

#477 batch add placeholder apps
  komga/Chart.yaml
  komga/TerminusManifest.yaml
  komga/owners
  komga/templates/deployment.yaml
  komga/values.yaml
  mongo/Chart.yaml
  mongo/TerminusManifest.yaml
  mongo/owners
  mongo/templates/deployment.yaml
  mongo/values.yaml
  ollama/Chart.yaml
  ollama/TerminusManifest.yaml
  ollama/owners
  ollama/templates/deployment.yaml
  ollama/values.yaml
  perplexica/Chart.yaml
  perplexica/TerminusManifest.yaml
  perplexica/owners
  perplexica/templates/deployment.yaml
  perplexica/values.yaml
  searxng/Chart.yaml
  searxng/TerminusManifest.yaml
  searxng/owners
  searxng/templates/deployment.yaml
  searxng/values.yaml
Labels: enhancement

#478 [NEW][dendrite][0.0.10]new app dendrite
  dendrite/Chart.yaml
  dendrite/TerminusManifest.yaml
  dendrite/owners
  dendrite/templates/Deployment.yaml
  dendrite/templates/Job.yaml
  dendrite/templates/RBAC.yaml
  dendrite/templates/Secret.yaml
  dendrite/templates/Service.yaml
  dendrite/templates/Web-Cinny.yaml
  dendrite/templates/Web-Element.yaml
  dendrite/templates/Web-Fluffychat.yaml
  dendrite/templates/Web-Hydrogen.yaml
  dendrite/values.yaml
Labels: NEW, waiting to submit

#479 [UPDATE][radarr][0.0.7]
  radarr/Chart.yaml
  radarr/README.md
  radarr/TerminusManifest.yaml
  radarr/owners
  radarr/templates/NOTES.txt
  radarr/templates/_helpers.tpl
  radarr/templates/deployment.yaml
Labels: UPDATE

#480 [UPDATE][lidarr][0.0.3]fix user Home
  lidarr/Chart.yaml
  lidarr/TerminusManifest.yaml
  lidarr/owners
  lidarr/templates/NOTES.txt
  lidarr/templates/_helpers.tpl
  lidarr/templates/deployment.yaml
  lidarr/values.yaml
Labels: UPDATE

#481 [UPDATE][radarr][0.0.9]
  radarr/Chart.yaml
  radarr/README.md
  radarr/TerminusManifest.yaml
Labels: UPDATE
