Repository Above-Os/terminus-apps, pull requests merged in 2024-06, with the labels that each got.

#415 Feat/batch update recommend r4extractor to latest
  r4business0522/templates/rank.yaml
  r4entertainment0522/templates/rank.yaml
  r4sport0522/templates/rank.yaml
  r4tech0522/templates/rank.yaml
  r4world0522/templates/rank.yaml
Labels: enhancement

#416 [UPDATE][bytebase][0.0.9]docs: add readme
  bytebase/Chart.yaml
  bytebase/README.md
  bytebase/TerminusManifest.yaml
Labels: UPDATE

#417 [UPDATE][bytebase][0.0.10] test md
  bytebase/Chart.yaml
  bytebase/README.md
  bytebase/TerminusManifest.yaml
Labels: UPDATE

#418 add readme for test
  affine/Chart.yaml
  affine/README.md
  affine/TerminusManifest.yaml
  jellyfin/Chart.yaml
  jellyfin/README.md
  jellyfin/TerminusManifest.yaml
  jellyfin/templates/deployment.yaml
  mastodon/Chart.yaml
  mastodon/README.md
  mastodon/TerminusManifest.yaml
  mastodon/templates/all.yaml
  obsidian/Chart.yaml
  obsidian/README.md
  obsidian/TerminusManifest.yaml
  obsidian/templates/deployment.yaml
Labels: enhancement

#420 Add mongo
  mongodb/.helmignore
  mongodb/Chart.yaml
  mongodb/TerminusManifest.yaml
  mongodb/owners
  mongodb/templates/NOTES.txt
  mongodb/templates/_helpers.tpl
  mongodb/templates/deployment.yaml
  mongodb/values.yaml
Labels: enhancement

#421 [UPDATE][mongodb][6.0.4]Add mongo
  mongodb/Chart.yaml
  mongodb/TerminusManifest.yaml
Labels: UPDATE, waiting to submit

#422 [UPDATE][mongodb][6.0.6]update deployment
  mongodb/templates/deployment.yaml
Labels: enhancement

#423 [UPDATE][bytebase][0.0.11]add middleware dependency
  bytebase/Chart.yaml
  bytebase/TerminusManifest.yaml
Labels: enhancement, UPDATE, waiting to submit

#424 unsuspend denny and denostr
  denny/.suspend
  denostr/.suspend
Labels: enhancement

#425 [UPDATE][mongodb][6.0.5]add onlyAdmin
  mongodb/Chart.yaml
  mongodb/TerminusManifest.yaml
Labels: UPDATE

#426 [UPDATE][denny][0.0.2]add mobile support
  denny/Chart.yaml
  denny/TerminusManifest.yaml
Labels: UPDATE

#427 [UPDATE][jellyfin][0.0.6]add onlyAdmin
  jellyfin/Chart.yaml
  jellyfin/TerminusManifest.yaml
Labels: UPDATE

#428 [UPDATE][mongodb][6.0.6]deployment for multi node
  mongodb/Chart.yaml
  mongodb/TerminusManifest.yaml
  mongodb/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#429 [NEW][devbox][0.0.1]add devbox
  devbox/.helmignore
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/owners
  devbox/templates/deployment.yaml
  devbox/values.yaml
Labels: NEW, waiting to submit

#430 [NEW][r4test][0.1.32]Add test recommend
  r4test/.helmignore
  r4test/Chart.yaml
  r4test/README.md
  r4test/TerminusManifest.yaml
  r4test/owners
  r4test/templates/NOTES.txt
  r4test/templates/_helpers.tpl
  r4test/templates/embedding.yaml
  r4test/templates/prerank.yaml
  r4test/templates/rank.yaml
  r4test/templates/train.yaml
  r4test/values.yaml
Labels: NEW

#432 [NEW][calendar][0.0.1]add calendar
  calendar/.helmignore
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/app.cfg
  calendar/owners
  calendar/templates/NOTES.txt
  calendar/templates/_helpers.tpl
  calendar/templates/calendar_deploy.yaml
  calendar/values.yaml
Labels: NEW, waiting to submit

#433 [UPDATE][r4test][0.1.33]
  r4test/Chart.yaml
  r4test/TerminusManifest.yaml
  r4test/templates/rank.yaml
Labels: UPDATE

#435 [UPDATE][calendar][0.0.2]add redis
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/app.cfg
  calendar/owners
  calendar/templates/calendar_deploy.yaml
Labels: UPDATE, waiting to submit

#436 [UPDATE][calendar][0.0.3]
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/templates/calendar_deploy.yaml
Labels: UPDATE

#438 [UPDATE][calendar][0.0.4]
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/templates/calendar_deploy.yaml
Labels: UPDATE, waiting to submit

#440 [UPDATE][r4test][0.1.34]
  r4test/Chart.yaml
  r4test/TerminusManifest.yaml
  r4test/templates/rank.yaml
Labels: UPDATE

#442 [UPDATE][devbox][0.0.2]feat: upgrade to v0.1.28
  devbox/Chart.yaml
  devbox/TerminusManifest.yaml
  devbox/owners
  devbox/templates/deployment.yaml
Labels: UPDATE

#444 batch update recommend
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/embedding.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/embedding.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/embedding.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/embedding.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/embedding.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/embedding.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: enhancement

#445 Feat/batch update recommend
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: enhancement

#441 [UPDATE][calendar][0.0.5]adjust resource and add description
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
  calendar/templates/calendar_deploy.yaml
Labels: UPDATE, waiting to submit

#446 Feat/batch update recommend
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
Labels: enhancement

#447 Feat/batch update recommend
  r4business/Chart.yaml
  r4business/TerminusManifest.yaml
  r4entertainment/Chart.yaml
  r4entertainment/TerminusManifest.yaml
  r4sport/Chart.yaml
  r4sport/TerminusManifest.yaml
  r4tech/Chart.yaml
  r4tech/TerminusManifest.yaml
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
  r4world/Chart.yaml
  r4world/TerminusManifest.yaml
Labels: enhancement

#448 [UPDATE][calendar][0.0.6]bump version for test
  calendar/Chart.yaml
  calendar/TerminusManifest.yaml
Labels: UPDATE

#449 [UPDATE][firefox][0.0.4]bump version for test
  firefox/Chart.yaml
  firefox/TerminusManifest.yaml
Labels: UPDATE

#451 [UPDATE][r4techbiz][0.1.38]Dev test
  r4techbiz/Chart.yaml
  r4techbiz/TerminusManifest.yaml
Labels: UPDATE
