Repository Above-Os/terminus-apps, pull requests merged in 2025-09, with the labels that each got.

#564 [UPDATE][wise][1.0.22]add sync remove function and fix bugs
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#566 [UPDATE][openedaispeech][1.0.5]feat: change to rbac provider
  openedaispeech/Chart.yaml
  openedaispeech/OlaresManifest.yaml
  openedaispeech/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#570 [UPDATE][sonarr][1.0.4]feat: change to rbac provider
  sonarr/Chart.yaml
  sonarr/OlaresManifest.yaml
  sonarr/templates/deployment.yaml
Labels: UPDATE

#573 [UPDATE][qbittorrent][1.0.3]feat: change to rbac provider
  qbittorrent/Chart.yaml
  qbittorrent/OlaresManifest.yaml
  qbittorrent/templates/deployment.yaml
Labels: UPDATE

#581 [UPDATE][qbittorrent][1.0.6]bump version
  qbittorrent/Chart.yaml
  qbittorrent/OlaresManifest.yaml
Labels: UPDATE

#572 [UPDATE][radarr][1.0.2]feat: change to rbac provider
  radarr/Chart.yaml
  radarr/OlaresManifest.yaml
  radarr/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#578 [UPDATE][deluge][1.0.3]feat: change to rbac provider
  deluge/Chart.yaml
  deluge/OlaresManifest.yaml
  deluge/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#579 [UPDATE][bazarr][1.0.4]change to rbac provider
  bazarr/Chart.yaml
  bazarr/OlaresManifest.yaml
  bazarr/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#575 [UPDATE][nzbget][1.0.3]feat: change to rbac provider
  nzbget/Chart.yaml
  nzbget/OlaresManifest.yaml
  nzbget/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#569 [UPDATE][transmission][1.0.4]feat: change to rbac provider
  transmission/Chart.yaml
  transmission/OlaresManifest.yaml
  transmission/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#568 [UPDATE][sickchill][1.0.5]feat: change to rbac provider
  sickchill/Chart.yaml
  sickchill/OlaresManifest.yaml
  sickchill/templates/deployment.yaml
Labels: UPDATE, waiting to submit

#584 [UPDATE][radarr][1.0.3]fix path
  radarr/Chart.yaml
  radarr/OlaresManifest.yaml
Labels: UPDATE

#585 [UPDATE][qbittorrent][1.0.7]fix path
  qbittorrent/Chart.yaml
  qbittorrent/OlaresManifest.yaml
Labels: UPDATE

#586 [UPDATE][readarr][1.0.3]fix path
  readarr/Chart.yaml
  readarr/OlaresManifest.yaml
Labels: UPDATE

#588 [UPDATE][sonarr][1.0.5]fix path
  sonarr/Chart.yaml
  sonarr/OlaresManifest.yaml
Labels: UPDATE, waiting to submit

#591 [UPDATE][homeassistant][1.0.7]upgrade version 2025.8.3 add supportArch arm64 (#1019)
  homeassistant/Chart.yaml
  homeassistant/OlaresManifest.yaml
  homeassistant/templates/deployment.yaml
Labels: UPDATE

#593 [UPDATE][bisheng][1.0.3]change provider to rbac
  bisheng/Chart.yaml
  bisheng/OlaresManifest.yaml
Labels: UPDATE

#594 [UPDATE][blinko][1.0.3]change provider to rbac
  blinko/Chart.yaml
  blinko/OlaresManifest.yaml
Labels: UPDATE

#595 [UPDATE][chinesesubfinder][1.0.4]change provider to rbac
  chinesesubfinder/Chart.yaml
  chinesesubfinder/OlaresManifest.yaml
  chinesesubfinder/templates/chinesesubfinder.yaml
Labels: UPDATE

#599 [UPDATE][deerflow][1.0.5]change provider to rbac
  deerflow/Chart.yaml
  deerflow/OlaresManifest.yaml
Labels: UPDATE

#606 [UPDATE][sdwebuiforgeshare][1.0.7]change provider to rbac
  sdwebuiforgeshare/Chart.yaml
  sdwebuiforgeshare/OlaresManifest.yaml
  sdwebuiforgeshare/templates/deployment.yaml
Labels: UPDATE

#607 [UPDATE][refly][1.0.2]change provider to rbac
  refly/Chart.yaml
  refly/OlaresManifest.yaml
Labels: UPDATE

#608 [UPDATE][ragflow][1.0.10]change provider to rbac
  ragflow/Chart.yaml
  ragflow/OlaresManifest.yaml
Labels: UPDATE

#610 [UPDATE][pdfmathtranslate][1.0.5]change provider to rbac
  pdfmathtranslate/Chart.yaml
  pdfmathtranslate/OlaresManifest.yaml
Labels: UPDATE

#615 [NEW][ollamaqwen314b][1.1.5]add app ollamaqwen314b
  ollamaqwen314b/Chart.yaml
  ollamaqwen314b/OlaresManifest.yaml
  ollamaqwen314b/i18n/en-US/OlaresManifest.yaml
  ollamaqwen314b/i18n/zh-CN/OlaresManifest.yaml
  ollamaqwen314b/owners
  ollamaqwen314b/templates/clientproxy.yaml
  ollamaqwen314b/templates/deployment.yaml
  ollamaqwen314b/values.yaml
Labels: NEW

#616 [UPDATE][dify][1.1.18]fix version
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#617 [UPDATE][jaaz][1.0.6] update provider
  jaaz/Chart.yaml
  jaaz/OlaresManifest.yaml
Labels: UPDATE

#618 [UPDATE][jaaz][1.0.7] update provider
  jaaz/Chart.yaml
  jaaz/OlaresManifest.yaml
  jaaz/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE, waiting to submit

#619 [UPDATE][jaaz][1.0.8] update provider
  jaaz/Chart.yaml
  jaaz/OlaresManifest.yaml
Labels: UPDATE, waiting to submit

#635 [UPDATE][wise][1.0.24]refactor rss server
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/knowledge/templates/rssubscribe.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#636 [UPDATE][wise][1.0.25]
  wise/Chart.yaml
  wise/OlaresManifest.yaml
  wise/knowledge/Chart.yaml
  wise/knowledge/templates/knowledge_deployment.yaml
  wise/knowledge/templates/rssubscribe.yaml
  wise/wise/Chart.yaml
  wise/wise/templates/front.yaml
Labels: UPDATE

#640 [UPDATE][firefox][1.0.5]test account
  firefox/Chart.yaml
  firefox/OlaresManifest.yaml
  firefox/price.yaml
Labels: UPDATE

#641 [UPDATE][firefox][1.0.6]test check
  firefox/Chart.yaml
  firefox/OlaresManifest.yaml
  firefox/price.yaml
Labels: UPDATE

#651 [UPDATE][ollamacogito14b][1.1.6]
  ollamacogito14b/Chart.yaml
  ollamacogito14b/OlaresManifest.yaml
Labels: UPDATE

#650 [UPDATE][ollamadeepseekr114b][1.1.7]
  ollamadeepseekr114b/Chart.yaml
  ollamadeepseekr114b/OlaresManifest.yaml
Labels: UPDATE, waiting to submit

#647 [UPDATE][ollamaminicpmv8b][1.1.6]
  ollamaminicpmv8b/Chart.yaml
  ollamaminicpmv8b/OlaresManifest.yaml
Labels: UPDATE

#645 [UPDATE][ollamaphi414b][1.1.6]
  ollamaphi414b/Chart.yaml
  ollamaphi414b/OlaresManifest.yaml
Labels: UPDATE

#644 [UPDATE][ollamaqwen314b][1.1.9]
  ollamaqwen314b/Chart.yaml
  ollamaqwen314b/OlaresManifest.yaml
Labels: UPDATE

#658 [UPDATE][merchant][0.3.7]fix schema url
  merchant/Chart.yaml
  merchant/OlaresManifest.yaml
  merchant/templates/deployment.yaml
Labels: UPDATE

#675 [UPDATE][merchant][0.3.17]update version
  merchant/Chart.yaml
  merchant/OlaresManifest.yaml
  merchant/templates/deployment.yaml
  merchant/templates/vc-system.yaml
  merchant/values.yaml
Labels: UPDATE, waiting to submit

#676 sync from prod 2025-09-22
  perplexica/Chart.yaml
  perplexica/OlaresManifest.yaml
  perplexica/templates/1-10-2/deployment.yaml
Labels: enhancement, waiting to submit

#672 [NEW][vllmqwen3reranker4b][1.0.1]add app vllmqwen3reranker4b
  vllmqwen3reranker4b/Chart.yaml
  vllmqwen3reranker4b/OlaresManifest.yaml
  vllmqwen3reranker4b/i18n/en-US/OlaresManifest.yaml
  vllmqwen3reranker4b/i18n/zh-CN/OlaresManifest.yaml
  vllmqwen3reranker4b/owners
  vllmqwen3reranker4b/templates/clientproxy.yaml
  vllmqwen3reranker4b/templates/deployment.yaml
  vllmqwen3reranker4b/values.yaml
Labels: NEW

#678 [UPDATE][vllmqwen3reranker4b][1.0.2]fix description
  vllmqwen3reranker4b/Chart.yaml
  vllmqwen3reranker4b/OlaresManifest.yaml
  vllmqwen3reranker4b/i18n/en-US/OlaresManifest.yaml
  vllmqwen3reranker4b/i18n/zh-CN/OlaresManifest.yaml
Labels: UPDATE

#669 [NEW][vllmqwen3embedding4b][1.0.1]add app vllmqwen3embedding4b
  vllmqwen3embedding4b/Chart.yaml
  vllmqwen3embedding4b/OlaresManifest.yaml
  vllmqwen3embedding4b/i18n/en-US/OlaresManifest.yaml
  vllmqwen3embedding4b/i18n/zh-CN/OlaresManifest.yaml
  vllmqwen3embedding4b/owners
  vllmqwen3embedding4b/templates/clientproxy.yaml
  vllmqwen3embedding4b/templates/deployment.yaml
  vllmqwen3embedding4b/values.yaml
Labels: NEW

#625 [NEW][ollamallama318b][1.1.5]add app ollamallama3.1_8b
  ollamallama318b/Chart.yaml
  ollamallama318b/OlaresManifest.yaml
  ollamallama318b/i18n/en-US/OlaresManifest.yaml
  ollamallama318b/i18n/zh-CN/OlaresManifest.yaml
  ollamallama318b/owners
  ollamallama318b/templates/clientproxy.yaml
  ollamallama318b/templates/deployment.yaml
  ollamallama318b/values.yaml
Labels: NEW, waiting to submit

#630 [NEW][ollamallava1613b][1.1.5]add app ollama: llava "1.613b; ?
  ollamallava1613b/Chart.yaml
  ollamallava1613b/OlaresManifest.yaml
  ollamallava1613b/i18n/en-US/OlaresManifest.yaml
  ollamallava1613b/i18n/zh-CN/OlaresManifest.yaml
  ollamallava1613b/owners
  ollamallava1613b/templates/clientproxy.yaml
  ollamallava1613b/templates/deployment.yaml
  ollamallava1613b/values.yaml
Labels: NEW, waiting to submit

#642 [UPDATE][firefox][1.0.8]test account
  firefox/Chart.yaml
  firefox/OlaresManifest.yaml
  firefox/price.yaml
Labels: UPDATE, waiting to submit

#684 batch fix os dependency
  ollamacogito14b/Chart.yaml
  ollamacogito14b/OlaresManifest.yaml
  ollamadeepseekr114b/Chart.yaml
  ollamadeepseekr114b/OlaresManifest.yaml
  ollamagemma327b/Chart.yaml
  ollamagemma327b/OlaresManifest.yaml
  ollamagemma327b/i18n/en-US/OlaresManifest.yaml
  ollamagemma327b/i18n/zh-CN/OlaresManifest.yaml
  ollamagptoss20b/Chart.yaml
  ollamagptoss20b/OlaresManifest.yaml
  ollamallama318b/Chart.yaml
  ollamallama318b/OlaresManifest.yaml
  ollamallava1613b/Chart.yaml
  ollamallava1613b/OlaresManifest.yaml
  ollamaminicpmv8b/Chart.yaml
  ollamaminicpmv8b/OlaresManifest.yaml
  ollamanomicembedtext/Chart.yaml
  ollamanomicembedtext/OlaresManifest.yaml
  ollamaphi414b/Chart.yaml
  ollamaphi414b/OlaresManifest.yaml
  ollamaqwen314b/Chart.yaml
  ollamaqwen314b/OlaresManifest.yaml
  vllmbgem3/Chart.yaml
  vllmbgem3/OlaresManifest.yaml
  vllmbgererankerv2m3/Chart.yaml
  vllmbgererankerv2m3/OlaresManifest.yaml
  vllmnomicembedtextv15/Chart.yaml
  vllmnomicembedtextv15/OlaresManifest.yaml
  vllmqwen3embedding4b/Chart.yaml
  vllmqwen3embedding4b/OlaresManifest.yaml
  vllmqwen3reranker4b/Chart.yaml
  vllmqwen3reranker4b/OlaresManifest.yaml
Labels: enhancement

#685 sync from prod 2025-09-30
  bisheng/Chart.yaml
  bisheng/OlaresManifest.yaml
  bisheng/templates/deployment.yaml
  comfyuishare/Chart.yaml
  comfyuishare/OlaresManifest.yaml
  comfyuishare/i18n/en-US/OlaresManifest.yaml
  comfyuishare/i18n/zh-CN/OlaresManifest.yaml
  comfyuishare/templates/deployment.yaml
  studio/Chart.yaml
  studio/OlaresManifest.yaml
  studio/studio/Chart.yaml
  studio/studioserver/Chart.yaml
Labels: enhancement, waiting to submit
