Repository Above-Os/terminus-apps, pull requests merged in 2025-04, with the labels that each got.

#542 [UPDATE][dify][1.1.15]bump version
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#543 [UPDATE][dify][1.1.16]test
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#544 [UPDATE][dify][1.1.17]
  dify/Chart.yaml
  dify/OlaresManifest.yaml
Labels: UPDATE

#545 [UPDATE][r4business][0.0.28]
  r4business/Chart.yaml
  r4business/OlaresManifest.yaml
  r4business/templates/embedding.yaml
  r4business/templates/prerank.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
Labels: UPDATE, waiting to submit

#513 [NEW][chaosmesh][0.0.1]
  chaosmesh/.helmignore
  chaosmesh/Chart.yaml
  chaosmesh/OlaresManifest.yaml
  chaosmesh/README.md
  chaosmesh/crds/chaos-mesh.org_awschaos.yaml
  chaosmesh/crds/chaos-mesh.org_azurechaos.yaml
  chaosmesh/crds/chaos-mesh.org_blockchaos.yaml
  chaosmesh/crds/chaos-mesh.org_dnschaos.yaml
  chaosmesh/crds/chaos-mesh.org_gcpchaos.yaml
  chaosmesh/crds/chaos-mesh.org_httpchaos.yaml
  chaosmesh/crds/chaos-mesh.org_iochaos.yaml
  chaosmesh/crds/chaos-mesh.org_jvmchaos.yaml
  chaosmesh/crds/chaos-mesh.org_kernelchaos.yaml
  chaosmesh/crds/chaos-mesh.org_networkchaos.yaml
  chaosmesh/crds/chaos-mesh.org_physicalmachinechaos.yaml
  chaosmesh/crds/chaos-mesh.org_physicalmachines.yaml
  chaosmesh/crds/chaos-mesh.org_podchaos.yaml
  chaosmesh/crds/chaos-mesh.org_podhttpchaos.yaml
  chaosmesh/crds/chaos-mesh.org_podiochaos.yaml
  chaosmesh/crds/chaos-mesh.org_podnetworkchaos.yaml
  chaosmesh/crds/chaos-mesh.org_remoteclusters.yaml
  chaosmesh/crds/chaos-mesh.org_schedules.yaml
  chaosmesh/crds/chaos-mesh.org_statuschecks.yaml
  chaosmesh/crds/chaos-mesh.org_stresschaos.yaml
  chaosmesh/crds/chaos-mesh.org_timechaos.yaml
  chaosmesh/crds/chaos-mesh.org_workflownodes.yaml
  chaosmesh/crds/chaos-mesh.org_workflows.yaml
  chaosmesh/i18n/en-US/OlaresManifest.yaml
  chaosmesh/i18n/zh-CN/OlaresManifest.yaml
  chaosmesh/owners
  chaosmesh/templates/NOTES.txt
  chaosmesh/templates/_certs.tpl
  chaosmesh/templates/_helpers.tpl
  chaosmesh/templates/cert-manager-certs.yaml
  chaosmesh/templates/chaos-daemon-daemonset.yaml
  chaosmesh/templates/chaos-daemon-rbac.yaml
  chaosmesh/templates/chaos-daemon-service.yaml
  chaosmesh/templates/chaos-dashboard-deployment.yaml
  chaosmesh/templates/chaos-dashboard-pvc.yaml
  chaosmesh/templates/chaos-dashboard-rbac.yaml
  chaosmesh/templates/controller-manager-deployment.yaml
  chaosmesh/templates/controller-manager-rbac.yaml
  chaosmesh/templates/controller-manager-service.yaml
  chaosmesh/templates/dns-configmap.yaml
  chaosmesh/templates/dns-deployment.yaml
  chaosmesh/templates/dns-rbac.yaml
  chaosmesh/templates/dns-service.yaml
  chaosmesh/templates/ingress.yaml
  chaosmesh/templates/mutating-admission-webhooks.yaml
  chaosmesh/templates/prometheus-configmap.yaml
  chaosmesh/templates/prometheus-deployment.yaml
  chaosmesh/templates/prometheus-rbac.yaml
  chaosmesh/templates/prometheus-service.yaml
  chaosmesh/templates/secrets-configuration.yaml
  chaosmesh/templates/validating-admission-webhooks.yaml
  chaosmesh/values.schema.json
  chaosmesh/values.yaml
Labels: NEW
