Repository Above-Os/terminus-apps, pull requests merged in 2025-01, with the labels that each got.

#522 Update recommend
  r4business/templates/prerank.yaml
  r4cnall/templates/prerank.yaml
  r4cntest/templates/prerank.yaml
  r4entertainment/templates/prerank.yaml
  r4sport/templates/prerank.yaml
  r4tech/templates/prerank.yaml
  r4techbiz/templates/prerank.yaml
  r4test/templates/prerank.yaml
  r4wechat/templates/prerank.yaml
  r4world/templates/prerank.yaml
Labels: enhancement

#523 r4 schedule
  r4business/templates/embedding.yaml
  r4business/templates/train.yaml
  r4cnall/templates/embedding.yaml
  r4cnall/templates/train.yaml
  r4cntest/templates/embedding.yaml
  r4cntest/templates/train.yaml
  r4entertainment/templates/embedding.yaml
  r4entertainment/templates/train.yaml
  r4sport/templates/embedding.yaml
  r4sport/templates/train.yaml
  r4tech/templates/embedding.yaml
  r4tech/templates/train.yaml
  r4techbiz/templates/embedding.yaml
  r4techbiz/templates/train.yaml
  r4wechat/templates/embedding.yaml
  r4wechat/templates/train.yaml
  r4world/templates/embedding.yaml
  r4world/templates/train.yaml
Labels: enhancement, waiting to submit

#524 Update recommend
  r4business/Chart.yaml
  r4business/OlaresManifest.yaml
  r4business/templates/rank.yaml
  r4business/templates/train.yaml
  r4cnall/templates/rank.yaml
  r4cnall/templates/train.yaml
  r4cntest/templates/rank.yaml
  r4cntest/templates/train.yaml
  r4entertainment/templates/rank.yaml
  r4entertainment/templates/train.yaml
  r4sport/templates/rank.yaml
  r4sport/templates/train.yaml
  r4tech/templates/rank.yaml
  r4tech/templates/train.yaml
  r4techbiz/templates/rank.yaml
  r4techbiz/templates/train.yaml
  r4test/templates/rank.yaml
  r4test/templates/train.yaml
  r4wechat/Chart.yaml
  r4wechat/OlaresManifest.yaml
  r4wechat/templates/rank.yaml
  r4wechat/templates/train.yaml
  r4world/Chart.yaml
  r4world/OlaresManifest.yaml
  r4world/templates/rank.yaml
  r4world/templates/train.yaml
Labels: enhancement

#525 [UPDATE][r4wechat][1.0.3]bump version to update
  r4wechat/Chart.yaml
  r4wechat/OlaresManifest.yaml
Labels: UPDATE

#526 [UPDATE][r4wechat][1.0.4]
  r4wechat/Chart.yaml
  r4wechat/OlaresManifest.yaml
  r4wechat/templates/rank.yaml
  r4wechat/templates/train.yaml
Labels: UPDATE

#527 [UPDATE][gitlabfusionclient][0.0.29]add mandatory
  gitlabfusionclient/Chart.yaml
  gitlabfusionclient/OlaresManifest.yaml
Labels: UPDATE

#529 [UPDATE][comfyui][1.0.15]fix: comfyui to 1.0.15
  comfyui/Chart.yaml
  comfyui/OlaresManifest.yaml
  comfyui/i18n/en-US/OlaresManifest.yaml
  comfyui/i18n/zh-CN/OlaresManifest.yaml
  comfyui/templates/configmap.yaml
  comfyui/templates/deployment.yaml
Labels: UPDATE

#530 [SUSPEND][sdwebui][0.1.13]offline
  sdwebui/.suspend
Labels: SUSPEND

#531 [UPDATE][n8n][0.1.0]test new git pull
  n8n/Chart.yaml
  n8n/OlaresManifest.yaml
Labels: UPDATE
